export type CurriculumSubjectOutline = {
  id: string
  title: string
  modules: string[]
}

export const cfaLevel1Outline: CurriculumSubjectOutline[] = [
  {
    id: 'ethics',
    title: 'Ethical and Professional Standards',
    modules: [
      'Ethics and Trust in the Investment Profession',
      'Code of Ethics and Standards of Professional Conduct',
      'Guidance for Standards I-VII',
      'Introduction to the Global Investment Performance Standards (GIPS)',
      'Ethics Application',
    ],
  },
  {
    id: 'quant',
    title: 'Quantitative Methods',
    modules: [
      'Rates and Returns',
      'Time Value of Money in Finance',
      'Statistical Measures of Asset Returns',
      'Probability Trees and Conditional Expectations',
      'Portfolio Mathematics',
      'Simulation Methods',
      'Estimation and Inference',
      'Hypothesis Testing',
      'Parametric and Non-Parametric Tests of Independence',
      'Simple Linear Regression',
      'Introduction to Big Data Techniques',
    ],
  },
  {
    id: 'economics',
    title: 'Economics',
    modules: [
      'The Firm and Market Structures',
      'Understanding Business Cycles',
      'Fiscal Policy',
      'Monetary Policy',
      'Introduction to Geopolitics',
      'International Trade',
      'Capital Flows and the FX Market',
      'Exchange Rate Calculations',
    ],
  },
  {
    id: 'financial-reporting',
    title: 'Financial Statement Analysis',
    modules: [
      'Introduction to Financial Statement Analysis',
      'Analyzing Income Statements',
      'Analyzing Balance Sheets',
      'Analyzing Statements of Cash Flows I',
      'Analyzing Statements of Cash Flows II',
      'Analysis of Inventories',
      'Analysis of Long-Term Assets',
      'Topics in Long-Term Liabilities and Equity',
      'Analysis of Income Taxes',
      'Financial Reporting Quality',
      'Financial Analysis Techniques',
      'Introduction to Financial Statement Modeling',
    ],
  },
  {
    id: 'corporate-issuers',
    title: 'Corporate Issuers',
    modules: [
      'Organizational Forms, Corporate Issuer Features, and Ownership',
      'Investors and Other Stakeholders',
      'Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits',
      'Working Capital and Liquidity',
      'Capital Investments and Capital Allocation',
      'Capital Structure',
      'Business Models',
    ],
  },
  {
    id: 'equity',
    title: 'Equity Investments',
    modules: [
      'Market Organization and Structure',
      'Security Market Indexes',
      'Market Efficiency',
      'Overview of Equity Securities',
      'Company Analysis: Past and Present',
      'Industry and Competitive Analysis',
      'Company Analysis: Forecasting',
      'Equity Valuation: Concepts and Basic Tools',
    ],
  },
  {
    id: 'fixed-income',
    title: 'Fixed Income',
    modules: [
      'Fixed-Income Instrument Features',
      'Fixed-Income Cash Flows and Types',
      'Fixed-Income Issuance and Trading',
      'Fixed-Income Markets for Corporate Issuers',
      'Fixed-Income Markets for Government Issuers',
      'Fixed-Income Bond Valuation: Prices and Yields',
      'Yield and Yield Spread Measures for Fixed-Rate Bonds',
      'Yield and Yield Spread Measures for Floating-Rate Instruments',
      'The Term Structure of Interest Rates: Spot, Par, and Forward Curves',
      'Interest Rate Risk and Return',
      'Yield-Based Bond Duration Measures and Properties',
      'Yield-Based Bond Convexity and Portfolio Properties',
      'Curve-Based and Empirical Fixed-Income Risk Measures',
      'Credit Risk',
      'Credit Analysis for Government Issuers',
      'Credit Analysis for Corporate Issuers',
      'Fixed-Income Securitization',
      'Asset-Backed Security (ABS) Instrument and Market Features',
      'Mortgage-Backed Security (MBS) Instrument and Market Features',
    ],
  },
  {
    id: 'derivatives',
    title: 'Derivatives',
    modules: [
      'Derivative Instrument and Derivative Market Features',
      'Forward Commitment and Contingent Claim Features and Instruments',
      'Derivative Benefits, Risks, and Issuer and Investor Uses',
      'Arbitrage, Replication, and the Cost of Carry in Pricing Derivatives',
      'Pricing and Valuation of Forward Contracts and for an Underlying with Varying Maturities',
      'Pricing and Valuation of Futures Contracts',
      'Pricing and Valuation of Interest Rates and Other Swaps',
      'Pricing and Valuation of Options',
      'Option Replication Using Put-Call Parity',
      'Valuing a Derivative Using a One-Period Binomial Model',
    ],
  },
  {
    id: 'alternative-investments',
    title: 'Alternative Investments',
    modules: [
      'Alternative Investment Features, Methods, and Structures',
      'Alternative Investment Performance and Returns',
      'Investments in Private Capital: Equity and Debt',
      'Real Estate and Infrastructure',
      'Natural Resources',
      'Hedge Funds',
      'Introduction to Digital Assets',
    ],
  },
  {
    id: 'portfolio',
    title: 'Portfolio Management',
    modules: [
      'Portfolio Risk and Return: Part I',
      'Portfolio Risk and Return: Part II',
      'Portfolio Management: An Overview',
      'Basics of Portfolio Planning and Construction',
      'The Behavioral Biases of Individuals',
      'Introduction to Risk Management',
    ],
  },
]

