export type FlashcardSubject =
  | 'Ethical and Professional Standards'
  | 'Quantitative Methods'
  | 'Economics'
  | 'Corporate Issuers'
  | 'Financial Statement Analysis'
  | 'Equity Investments'
  | 'Fixed Income'
  | 'Derivatives'
  | 'Alternative Investments'
  | 'Portfolio Management'

export type Flashcard = {
  id: string
  subject: FlashcardSubject
  module: string
  title: string
  prompt: string
  answer: string
  memoryHook: string
  tags: string[]
}

export const formulaFlashcards: Flashcard[] = [
  {
    id: 'quant-hpr',
    subject: 'Quantitative Methods',
    module: 'Rates and Returns',
    title: 'Holding Period Return',
    prompt: 'What is the holding period return formula?',
    answer: 'HPR = (Ending value - Beginning value + Income) / Beginning value',
    memoryHook: 'Price change plus income, all divided by what you paid at the start.',
    tags: ['return', 'core'],
  },
  {
    id: 'quant-geometric-mean',
    subject: 'Quantitative Methods',
    module: 'Rates and Returns',
    title: 'Geometric Mean Return',
    prompt: 'How do you annualize compounded returns across periods?',
    answer: 'Geometric mean = [(1 + R1)(1 + R2)...(1 + Rn)]^(1/n) - 1',
    memoryHook: 'Multiply growth factors first, then take the root.',
    tags: ['return', 'annualization'],
  },
  {
    id: 'quant-ear',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    title: 'Effective Annual Rate',
    prompt: 'What is the EAR formula?',
    answer: 'EAR = (1 + periodic rate)^m - 1',
    memoryHook: 'Nominal rate becomes real only after compounding m times.',
    tags: ['tvm', 'interest-rate'],
  },
  {
    id: 'quant-pv-single',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    title: 'Present Value of a Single Cash Flow',
    prompt: 'How do you discount a single future cash flow?',
    answer: 'PV = FV / (1 + r)^N',
    memoryHook: 'Future money shrinks by the compounding factor.',
    tags: ['tvm', 'discounting'],
  },
  {
    id: 'quant-annuity',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    title: 'Present Value of an Ordinary Annuity',
    prompt: 'What is the present value formula for an ordinary annuity?',
    answer: 'PV annuity = PMT × [1 - (1 + r)^(-N)] / r',
    memoryHook: 'A level stream is one payment size times the annuity factor.',
    tags: ['tvm', 'annuity'],
  },
  {
    id: 'quant-perpetuity',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    title: 'Present Value of a Perpetuity',
    prompt: 'What is the PV formula for a perpetuity?',
    answer: 'PV perpetuity = PMT / r',
    memoryHook: 'Infinite equal payments collapse to payment over rate.',
    tags: ['tvm', 'perpetuity'],
  },
  {
    id: 'quant-bayes',
    subject: 'Quantitative Methods',
    module: 'Probability Trees and Conditional Expectations',
    title: 'Bayes Formula',
    prompt: 'What is the Bayes formula setup used in CFA Level I?',
    answer: 'P(A|B) = [P(B|A) × P(A)] / P(B)',
    memoryHook: 'Posterior equals likelihood times prior over total evidence.',
    tags: ['probability', 'bayes'],
  },
  {
    id: 'quant-covariance',
    subject: 'Quantitative Methods',
    module: 'Portfolio Mathematics',
    title: 'Two-Asset Portfolio Variance',
    prompt: 'What is the variance formula for a two-asset portfolio?',
    answer: 'Var(p) = w1^2σ1^2 + w2^2σ2^2 + 2w1w2ρ12σ1σ2',
    memoryHook: 'Two solo risk terms plus one interaction term.',
    tags: ['portfolio', 'variance'],
  },
  {
    id: 'quant-confidence-interval',
    subject: 'Quantitative Methods',
    module: 'Estimation and Inference',
    title: 'Confidence Interval',
    prompt: 'What is the general confidence interval format?',
    answer: 'Point estimate ± reliability factor × standard error',
    memoryHook: 'Estimate in the middle, uncertainty on both sides.',
    tags: ['inference', 'confidence-interval'],
  },
  {
    id: 'quant-t-stat',
    subject: 'Quantitative Methods',
    module: 'Hypothesis Testing',
    title: 't-Statistic',
    prompt: 'What is the generic t-statistic formula?',
    answer: 't = (sample statistic - hypothesized value) / standard error',
    memoryHook: 'Distance from the null measured in standard errors.',
    tags: ['hypothesis-testing', 't-stat'],
  },
  {
    id: 'quant-regression-line',
    subject: 'Quantitative Methods',
    module: 'Simple Linear Regression',
    title: 'Regression Equation',
    prompt: 'What is the simple linear regression form?',
    answer: 'Yi = b0 + b1Xi + εi',
    memoryHook: 'Intercept plus slope times X plus noise.',
    tags: ['regression', 'model'],
  },
  {
    id: 'econ-elasticity',
    subject: 'Economics',
    module: 'The Firm and Market Structures',
    title: 'Price Elasticity of Demand',
    prompt: 'What is the price elasticity of demand formula?',
    answer: 'Elasticity = % change in quantity demanded / % change in price',
    memoryHook: 'Demand sensitivity equals quantity move over price move.',
    tags: ['elasticity', 'micro'],
  },
  {
    id: 'econ-fiscal-multiplier',
    subject: 'Economics',
    module: 'Fiscal Policy',
    title: 'Fiscal Multiplier',
    prompt: 'What is the simple fiscal multiplier formula?',
    answer: 'Multiplier = 1 / (1 - MPC)',
    memoryHook: 'The closer MPC is to 1, the larger the ripple effect.',
    tags: ['macro', 'fiscal-policy'],
  },
  {
    id: 'econ-real-fx',
    subject: 'Economics',
    module: 'Exchange Rate Calculations',
    title: 'Real Exchange Rate',
    prompt: 'How is the real exchange rate expressed?',
    answer: 'Real FX rate = Nominal FX rate × Domestic price level / Foreign price level',
    memoryHook: 'Nominal FX adjusted for relative inflation.',
    tags: ['fx', 'macro'],
  },
  {
    id: 'corp-npv',
    subject: 'Corporate Issuers',
    module: 'Capital Investments and Capital Allocation',
    title: 'Net Present Value',
    prompt: 'What is the NPV rule and formula idea?',
    answer: 'NPV = Present value of cash inflows - Present value of cash outflows',
    memoryHook: 'Create value when discounted inflows beat the upfront spend.',
    tags: ['capital-budgeting', 'npv'],
  },
  {
    id: 'corp-irr',
    subject: 'Corporate Issuers',
    module: 'Capital Investments and Capital Allocation',
    title: 'Internal Rate of Return',
    prompt: 'How is IRR defined?',
    answer: 'IRR is the discount rate that sets NPV to zero',
    memoryHook: 'IRR is the breakeven discount rate for the project.',
    tags: ['capital-budgeting', 'irr'],
  },
  {
    id: 'corp-wacc',
    subject: 'Corporate Issuers',
    module: 'Capital Structure',
    title: 'Weighted Average Cost of Capital',
    prompt: 'What is the WACC formula?',
    answer: 'WACC = wd × rd × (1 - tax rate) + we × re + wp × rp',
    memoryHook: 'Blend the required return of every capital source, with debt after tax.',
    tags: ['wacc', 'capital-structure'],
  },
  {
    id: 'corp-cash-conversion',
    subject: 'Corporate Issuers',
    module: 'Working Capital and Liquidity',
    title: 'Cash Conversion Cycle',
    prompt: 'What is the cash conversion cycle formula?',
    answer: 'CCC = Days inventory outstanding + Days sales outstanding - Days payables outstanding',
    memoryHook: 'Inventory days plus collection days minus supplier float.',
    tags: ['working-capital', 'liquidity'],
  },
  {
    id: 'fsa-basic-eps',
    subject: 'Financial Statement Analysis',
    module: 'Analyzing Income Statements',
    title: 'Basic EPS',
    prompt: 'What is the basic EPS formula?',
    answer: 'Basic EPS = (Net income - Preferred dividends) / Weighted average common shares outstanding',
    memoryHook: 'Common shareholders only, over the average share count.',
    tags: ['eps', 'income-statement'],
  },
  {
    id: 'fsa-current-ratio',
    subject: 'Financial Statement Analysis',
    module: 'Financial Analysis Techniques',
    title: 'Current Ratio',
    prompt: 'What is the current ratio formula?',
    answer: 'Current ratio = Current assets / Current liabilities',
    memoryHook: 'Short-term resources divided by short-term obligations.',
    tags: ['ratio', 'liquidity'],
  },
  {
    id: 'fsa-quick-ratio',
    subject: 'Financial Statement Analysis',
    module: 'Financial Analysis Techniques',
    title: 'Quick Ratio',
    prompt: 'What is the quick ratio formula?',
    answer: 'Quick ratio = (Cash + Marketable securities + Receivables) / Current liabilities',
    memoryHook: 'Strip out the slower inventory layer.',
    tags: ['ratio', 'liquidity'],
  },
  {
    id: 'fsa-dupont',
    subject: 'Financial Statement Analysis',
    module: 'Financial Analysis Techniques',
    title: 'Three-Part DuPont',
    prompt: 'What is the three-part DuPont decomposition of ROE?',
    answer: 'ROE = Net profit margin × Asset turnover × Financial leverage',
    memoryHook: 'Profitability times efficiency times leverage.',
    tags: ['dupont', 'roe'],
  },
  {
    id: 'fsa-fcff',
    subject: 'Financial Statement Analysis',
    module: 'Financial Analysis Techniques',
    title: 'Free Cash Flow to the Firm',
    prompt: 'What is a common FCFF expression?',
    answer: 'FCFF = CFO + Interest × (1 - tax rate) - Capital expenditures',
    memoryHook: 'Start from cash from operations, add back after-tax debt cost, subtract reinvestment.',
    tags: ['cash-flow', 'fcff'],
  },
  {
    id: 'equity-gordon',
    subject: 'Equity Investments',
    module: 'Equity Valuation: Concepts and Basic Tools',
    title: 'Gordon Growth Model',
    prompt: 'What is the constant-growth dividend discount model?',
    answer: 'V0 = D1 / (r - g)',
    memoryHook: 'Next dividend over required return minus growth.',
    tags: ['valuation', 'ddm'],
  },
  {
    id: 'equity-fcfe',
    subject: 'Equity Investments',
    module: 'Equity Valuation: Concepts and Basic Tools',
    title: 'FCFE Value',
    prompt: 'How is equity value linked to FCFE in a stable growth setting?',
    answer: 'Equity value = FCFE1 / (required return - growth)',
    memoryHook: 'Same Gordon logic, but using equity cash flow instead of dividends.',
    tags: ['valuation', 'fcfe'],
  },
  {
    id: 'equity-capm',
    subject: 'Equity Investments',
    module: 'Company Analysis: Forecasting',
    title: 'CAPM Required Return',
    prompt: 'What is the CAPM formula?',
    answer: 'Required return = Risk-free rate + Beta × (Market return - Risk-free rate)',
    memoryHook: 'Risk-free base plus market risk premium scaled by beta.',
    tags: ['capm', 'beta'],
  },
  {
    id: 'fixed-bond-price',
    subject: 'Fixed Income',
    module: 'Fixed-Income Bond Valuation: Prices and Yields',
    title: 'Bond Price',
    prompt: 'How is a plain-vanilla bond priced?',
    answer: 'Bond price = Present value of coupon payments + Present value of par value',
    memoryHook: 'A bond is just an annuity plus a lump sum.',
    tags: ['bond-pricing', 'valuation'],
  },
  {
    id: 'fixed-current-yield',
    subject: 'Fixed Income',
    module: 'Yield and Yield Spread Measures for Fixed-Rate Bonds',
    title: 'Current Yield',
    prompt: 'What is the current yield formula?',
    answer: 'Current yield = Annual coupon payment / Bond price',
    memoryHook: 'Coupon income today divided by what the bond costs now.',
    tags: ['yield', 'bond'],
  },
  {
    id: 'fixed-macaulay-duration',
    subject: 'Fixed Income',
    module: 'Yield-Based Bond Duration Measures and Properties',
    title: 'Modified Duration Link',
    prompt: 'How do Macaulay duration and modified duration connect?',
    answer: 'Modified duration = Macaulay duration / (1 + yield per period)',
    memoryHook: 'Modified duration is the price-sensitivity version of Macaulay duration.',
    tags: ['duration', 'interest-rate-risk'],
  },
  {
    id: 'fixed-duration-approx',
    subject: 'Fixed Income',
    module: 'Yield-Based Bond Duration Measures and Properties',
    title: 'Duration Approximation',
    prompt: 'How do you approximate price change using duration?',
    answer: '%ΔP ≈ -Modified duration × Δyield',
    memoryHook: 'Prices move opposite to yields, scaled by duration.',
    tags: ['duration', 'approximation'],
  },
  {
    id: 'fixed-convexity',
    subject: 'Fixed Income',
    module: 'Yield-Based Bond Convexity and Portfolio Properties',
    title: 'Duration with Convexity',
    prompt: 'How do you improve the duration-only price approximation?',
    answer: '%ΔP ≈ -Modified duration × Δyield + 0.5 × Convexity × (Δyield)^2',
    memoryHook: 'Duration gives the line, convexity bends it back into shape.',
    tags: ['convexity', 'interest-rate-risk'],
  },
  {
    id: 'fixed-bpv',
    subject: 'Fixed Income',
    module: 'Yield-Based Bond Duration Measures and Properties',
    title: 'Basis Point Value',
    prompt: 'What is BPV conceptually?',
    answer: 'BPV is the approximate price change of a bond for a 1 bp change in yield',
    memoryHook: 'One basis point of rate move, one small cash price impact.',
    tags: ['bpv', 'risk'],
  },
  {
    id: 'deriv-forward-price',
    subject: 'Derivatives',
    module: 'Arbitrage, Replication, and the Cost of Carry in Pricing Derivatives',
    title: 'Forward Price',
    prompt: 'What is the basic no-arbitrage forward price with no carry costs or benefits?',
    answer: 'Forward price = Spot price × (1 + risk-free rate)^T',
    memoryHook: 'Spot grown at financing cost until maturity.',
    tags: ['forward', 'cost-of-carry'],
  },
  {
    id: 'deriv-put-call-parity',
    subject: 'Derivatives',
    module: 'Option Replication Using Put-Call Parity',
    title: 'Put-Call Parity',
    prompt: 'What is the standard European put-call parity relationship?',
    answer: 'Call + PV(strike) = Put + Spot',
    memoryHook: 'A call plus cash can replicate a protective stock position.',
    tags: ['options', 'put-call-parity'],
  },
  {
    id: 'deriv-binomial',
    subject: 'Derivatives',
    module: 'Valuing a Derivative Using a One-Period Binomial Model',
    title: 'Binomial Option Value',
    prompt: 'How is a one-period option priced in the risk-neutral framework?',
    answer: 'Option value = [p × Cu + (1 - p) × Cd] / (1 + risk-free rate)',
    memoryHook: 'Discount the expected payoff using risk-neutral probabilities.',
    tags: ['options', 'binomial'],
  },
  {
    id: 'alts-fees',
    subject: 'Alternative Investments',
    module: 'Alternative Investment Performance and Returns',
    title: 'Two-and-Twenty Fee Logic',
    prompt: 'How should you think about hedge fund two-and-twenty fees on exam questions?',
    answer: 'Investor net return = Gross return - Management fee - Incentive fee on eligible profits',
    memoryHook: 'Management fee comes first; incentive fee bites into the remaining gains.',
    tags: ['hedge-funds', 'fees'],
  },
  {
    id: 'portfolio-sharpe',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return: Part II',
    title: 'Sharpe Ratio',
    prompt: 'What is the Sharpe ratio formula?',
    answer: 'Sharpe ratio = (Portfolio return - Risk-free rate) / Portfolio standard deviation',
    memoryHook: 'Excess return per unit of total risk.',
    tags: ['sharpe', 'performance'],
  },
  {
    id: 'portfolio-treynor',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return: Part II',
    title: 'Treynor Ratio',
    prompt: 'What is the Treynor ratio formula?',
    answer: 'Treynor ratio = (Portfolio return - Risk-free rate) / Portfolio beta',
    memoryHook: 'Excess return per unit of systematic risk.',
    tags: ['treynor', 'performance'],
  },
  {
    id: 'portfolio-cal',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return: Part II',
    title: 'Capital Allocation Line',
    prompt: 'What does the slope of the CAL represent?',
    answer: 'The slope of the CAL equals the Sharpe ratio of the risky portfolio',
    memoryHook: 'Steeper CAL means more excess return per unit of risk.',
    tags: ['cal', 'portfolio-theory'],
  },
  {
    id: 'ethics-trust',
    subject: 'Ethical and Professional Standards',
    module: 'Ethics and Trust in the Investment Profession',
    title: 'Ethics Priority Rule',
    prompt: 'When an ethics vignette feels ambiguous, what should the candidate prioritize first?',
    answer: 'Protect market integrity, client interests, and independence before convenience or business pressure',
    memoryHook: 'Integrity before advantage.',
    tags: ['ethics', 'decision-rule'],
  },
]

export const flashcardSubjects = Array.from(new Set(formulaFlashcards.map((card) => card.subject)))

export type FlashcardKind = 'formula' | 'concept' | 'process' | 'warning'

export type FlashcardCard = {
  id: string
  subjectId: string
  subjectTitle: string
  subjectWeight: string
  topicId: string
  topicTitle: string
  kind: FlashcardKind
  front: string
  back: string
  hint: string
  tags: string[]
  difficulty: 1 | 2 | 3 | 4 | 5
}

export type FlashcardTopicGroup = {
  topicId: string
  topicTitle: string
  cards: FlashcardCard[]
}

export type FlashcardSubjectGroup = {
  subjectId: string
  subjectTitle: string
  subjectWeight: string
  topics: FlashcardTopicGroup[]
}

const syllabusFlashcards: FlashcardSubjectGroup[] = [
  {
    subjectId: 'ethics',
    subjectTitle: 'Ethical and Professional Standards',
    subjectWeight: '15-20%',
    topics: [
      {
        topicId: 'ethics-standards',
        topicTitle: 'Standards and decision making',
        cards: [
          {
            id: 'ethics-standards-ethics-vs-legal',
            subjectId: 'ethics',
            subjectTitle: 'Ethical and Professional Standards',
            subjectWeight: '15-20%',
            topicId: 'ethics-standards',
            topicTitle: 'Standards and decision making',
            kind: 'concept',
            front: 'How should you think about ethics versus legality?',
            back: 'A legal action can still be unethical. Use the CFA Standards when they are stricter than the law and protect clients, markets, and your integrity.',
            hint: 'Ethics is the higher bar.',
            tags: ['ethics', 'standards', 'judgment'],
            difficulty: 2,
          },
          {
            id: 'ethics-standards-framework',
            subjectId: 'ethics',
            subjectTitle: 'Ethical and Professional Standards',
            subjectWeight: '15-20%',
            topicId: 'ethics-standards',
            topicTitle: 'Standards and decision making',
            kind: 'process',
            front: 'What is a clean ethics decision workflow?',
            back: 'Identify facts, list duties and conflicts, map the applicable Standard, compare reasonable actions, then choose the most protective action for investors and the market.',
            hint: 'Facts first, then standards.',
            tags: ['ethics', 'decision flow', 'process'],
            difficulty: 2,
          },
          {
            id: 'ethics-standards-mnp',
            subjectId: 'ethics',
            subjectTitle: 'Ethical and Professional Standards',
            subjectWeight: '15-20%',
            topicId: 'ethics-standards',
            topicTitle: 'Standards and decision making',
            kind: 'warning',
            front: 'What do you do with material nonpublic information?',
            back: 'Do not trade, tip, or use it for benefit. Disengage from the idea and avoid any action that would exploit the information edge.',
            hint: 'No trade, no tip, no use.',
            tags: ['ethics', 'inside information', 'warning'],
            difficulty: 2,
          },
        ],
      },
      {
        topicId: 'ethics-gips',
        topicTitle: 'GIPS and performance reporting',
        cards: [
          {
            id: 'ethics-gips-purpose',
            subjectId: 'ethics',
            subjectTitle: 'Ethical and Professional Standards',
            subjectWeight: '15-20%',
            topicId: 'ethics-gips',
            topicTitle: 'GIPS and performance reporting',
            kind: 'concept',
            front: 'Why does GIPS matter?',
            back: 'It creates fair, comparable, and complete performance reporting so investors can compare firms without cherry-picked results.',
            hint: 'Fair comparison is the point.',
            tags: ['gips', 'performance', 'reporting'],
            difficulty: 2,
          },
          {
            id: 'ethics-gips-disclosure',
            subjectId: 'ethics',
            subjectTitle: 'Ethical and Professional Standards',
            subjectWeight: '15-20%',
            topicId: 'ethics-gips',
            topicTitle: 'GIPS and performance reporting',
            kind: 'warning',
            front: 'What is the biggest GIPS exam trap?',
            back: 'Incomplete disclosure. A claim can fail if the presentation omits needed context, fees, or a clear explanation of the composite used.',
            hint: 'If it is not disclosed, it is risky.',
            tags: ['gips', 'disclosure', 'trap'],
            difficulty: 3,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'quant',
    subjectTitle: 'Quantitative Methods',
    subjectWeight: '6-9%',
    topics: [
      {
        topicId: 'quant-rates',
        topicTitle: 'Rates and returns',
        cards: [
          {
            id: 'quant-hpr',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-rates',
            topicTitle: 'Rates and returns',
            kind: 'formula',
            front: 'Holding period return',
            back: 'HPR = (P1 - P0 + D1) / P0. Split it into capital gain yield plus income yield when the question wants the pieces.',
            hint: 'Price change plus cash income.',
            tags: ['return', 'formula', 'pricing'],
            difficulty: 2,
          },
          {
            id: 'quant-geom-mean',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-rates',
            topicTitle: 'Rates and returns',
            kind: 'formula',
            front: 'Geometric mean return',
            back: '[(1 + R1)(1 + R2)...(1 + Rn)]^(1/n) - 1. Use it when compounding over multiple periods.',
            hint: 'Compounding, not averaging.',
            tags: ['return', 'compound', 'formula'],
            difficulty: 3,
          },
          {
            id: 'quant-ear',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-rates',
            topicTitle: 'Rates and returns',
            kind: 'formula',
            front: 'Effective annual rate from a stated annual rate',
            back: 'EAR = (1 + SAR / m)^m - 1. More compounding periods make the effective rate higher.',
            hint: 'Convert stated to effective.',
            tags: ['interest', 'ear', 'formula'],
            difficulty: 3,
          },
        ],
      },
      {
        topicId: 'quant-time-value',
        topicTitle: 'Time value of money',
        cards: [
          {
            id: 'quant-pvfv',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-time-value',
            topicTitle: 'Time value of money',
            kind: 'formula',
            front: 'Present value of a single cash flow',
            back: 'PV = FV / (1 + r)^N. For multiple cash flows, discount each one separately and sum them.',
            hint: 'Discount back from the future.',
            tags: ['pv', 'fv', 'discounting'],
            difficulty: 2,
          },
          {
            id: 'quant-annuity',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-time-value',
            topicTitle: 'Time value of money',
            kind: 'formula',
            front: 'Ordinary annuity versus annuity due',
            back: 'An ordinary annuity pays at period end; an annuity due pays at period start and is worth one period more in PV terms.',
            hint: 'Timing changes value.',
            tags: ['annuity', 'timing', 'formula'],
            difficulty: 3,
          },
          {
            id: 'quant-continuous',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-time-value',
            topicTitle: 'Time value of money',
            kind: 'formula',
            front: 'Continuously compounded return',
            back: 'rcc = ln(1 + HPR). The reverse is HPR = e^(rcc) - 1.',
            hint: 'Log returns use ln.',
            tags: ['continuous', 'log return', 'formula'],
            difficulty: 3,
          },
        ],
      },
      {
        topicId: 'quant-statistics',
        topicTitle: 'Statistics and probability',
        cards: [
          {
            id: 'quant-ci',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-statistics',
            topicTitle: 'Statistics and probability',
            kind: 'formula',
            front: 'Confidence interval for a mean',
            back: 'Point estimate +/- critical value x standard error. The interval widens when uncertainty rises.',
            hint: 'Estimate plus/minus uncertainty.',
            tags: ['confidence interval', 'statistics', 'formula'],
            difficulty: 3,
          },
          {
            id: 'quant-bayes',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-statistics',
            topicTitle: 'Statistics and probability',
            kind: 'formula',
            front: "Bayes' theorem",
            back: 'Posterior probability = (likelihood x prior) / evidence. It updates beliefs once new information arrives.',
            hint: 'Update the prior.',
            tags: ['bayes', 'probability', 'formula'],
            difficulty: 4,
          },
          {
            id: 'quant-corr',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-statistics',
            topicTitle: 'Statistics and probability',
            kind: 'formula',
            front: 'Covariance and correlation',
            back: 'Correlation = covariance / (stdev1 x stdev2). Correlation tells you direction and strength on a standardized scale.',
            hint: 'Normalize the covariance.',
            tags: ['covariance', 'correlation', 'risk'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'quant-portfolio',
        topicTitle: 'Portfolio math',
        cards: [
          {
            id: 'quant-portfolio-var',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-portfolio',
            topicTitle: 'Portfolio math',
            kind: 'formula',
            front: 'Two-asset portfolio variance',
            back: 'Use the weighted sum of individual variances plus the covariance term. Diversification helps when correlation is below +1.',
            hint: 'Weights plus covariance.',
            tags: ['portfolio', 'variance', 'formula'],
            difficulty: 4,
          },
          {
            id: 'quant-se',
            subjectId: 'quant',
            subjectTitle: 'Quantitative Methods',
            subjectWeight: '6-9%',
            topicId: 'quant-portfolio',
            topicTitle: 'Portfolio math',
            kind: 'formula',
            front: 'Standard error of the sample mean',
            back: 'SE = sample standard deviation / sqrt(n) when population sigma is unknown. More observations shrink sampling error.',
            hint: 'More data, lower error.',
            tags: ['sampling', 'standard error', 'statistics'],
            difficulty: 3,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'economics',
    subjectTitle: 'Economics',
    subjectWeight: '6-9%',
    topics: [
      {
        topicId: 'econ-micro',
        topicTitle: 'Microeconomics',
        cards: [
          {
            id: 'econ-elasticity',
            subjectId: 'economics',
            subjectTitle: 'Economics',
            subjectWeight: '6-9%',
            topicId: 'econ-micro',
            topicTitle: 'Microeconomics',
            kind: 'formula',
            front: 'Price elasticity of demand',
            back: 'Elasticity = % change in quantity demanded / % change in price. Inelastic demand means quantity barely moves when price changes.',
            hint: 'Responsiveness to price.',
            tags: ['elasticity', 'demand', 'formula'],
            difficulty: 3,
          },
          {
            id: 'econ-cross-price',
            subjectId: 'economics',
            subjectTitle: 'Economics',
            subjectWeight: '6-9%',
            topicId: 'econ-micro',
            topicTitle: 'Microeconomics',
            kind: 'concept',
            front: 'What does cross-price elasticity tell you?',
            back: 'Whether goods are substitutes or complements. Positive values suggest substitutes; negative values suggest complements.',
            hint: 'Cross-price reveals the relationship.',
            tags: ['micro', 'substitutes', 'complements'],
            difficulty: 2,
          },
          {
            id: 'econ-costs',
            subjectId: 'economics',
            subjectTitle: 'Economics',
            subjectWeight: '6-9%',
            topicId: 'econ-micro',
            topicTitle: 'Microeconomics',
            kind: 'process',
            front: 'What matters for firm shutdown and exit?',
            back: 'Compare price to average variable cost in the short run; shutdown is about covering variable costs, while exit is a longer-run capital decision.',
            hint: 'Short run uses variable cost.',
            tags: ['firm', 'shutdown', 'costs'],
            difficulty: 3,
          },
        ],
      },
      {
        topicId: 'econ-macro',
        topicTitle: 'Macro and currency',
        cards: [
          {
            id: 'econ-gdp-deflator',
            subjectId: 'economics',
            subjectTitle: 'Economics',
            subjectWeight: '6-9%',
            topicId: 'econ-macro',
            topicTitle: 'Macro and currency',
            kind: 'formula',
            front: 'GDP deflator',
            back: 'GDP deflator = nominal GDP / real GDP x 100. It is a broad price measure built from domestic output.',
            hint: 'Nominal over real.',
            tags: ['gdp', 'inflation', 'formula'],
            difficulty: 3,
          },
          {
            id: 'econ-fiscal-multiplier',
            subjectId: 'economics',
            subjectTitle: 'Economics',
            subjectWeight: '6-9%',
            topicId: 'econ-macro',
            topicTitle: 'Macro and currency',
            kind: 'formula',
            front: 'Fiscal multiplier',
            back: 'Multiplier = 1 / (1 - MPC) in the simple case. Higher marginal propensity to consume means a bigger output effect.',
            hint: 'Consumption drives the multiplier.',
            tags: ['fiscal policy', 'macro', 'formula'],
            difficulty: 4,
          },
          {
            id: 'econ-fx-forward',
            subjectId: 'economics',
            subjectTitle: 'Economics',
            subjectWeight: '6-9%',
            topicId: 'econ-macro',
            topicTitle: 'Macro and currency',
            kind: 'formula',
            front: 'Forward exchange rate intuition',
            back: 'A currency with the higher interest rate usually trades at a forward discount versus the lower-rate currency under no-arbitrage logic.',
            hint: 'Rate differential drives the forward.',
            tags: ['fx', 'forward rate', 'arbitrage'],
            difficulty: 4,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'financial-reporting',
    subjectTitle: 'Financial Statement Analysis',
    subjectWeight: '11-14%',
    topics: [
      {
        topicId: 'fsa-eps',
        topicTitle: 'Earnings and cash flow',
        cards: [
          {
            id: 'fsa-basic-eps',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-eps',
            topicTitle: 'Earnings and cash flow',
            kind: 'formula',
            front: 'Basic EPS',
            back: 'Basic EPS = (net income - preferred dividends) / weighted average common shares outstanding.',
            hint: 'Income available to common shareholders.',
            tags: ['eps', 'earnings', 'formula'],
            difficulty: 3,
          },
          {
            id: 'fsa-diluted-eps',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-eps',
            topicTitle: 'Earnings and cash flow',
            kind: 'formula',
            front: 'Diluted EPS',
            back: 'Diluted EPS assumes dilutive securities are exercised or converted. Use the if-converted or treasury stock approach as needed.',
            hint: 'Think dilution, not basic.',
            tags: ['eps', 'diluted', 'shares'],
            difficulty: 4,
          },
          {
            id: 'fsa-fcff-fcfe',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-eps',
            topicTitle: 'Earnings and cash flow',
            kind: 'formula',
            front: 'FCFF versus FCFE',
            back: 'FCFF is cash flow available to all capital providers; FCFE is cash flow available only to common equity after debt effects.',
            hint: 'Firm cash flow versus equity cash flow.',
            tags: ['cash flow', 'fcff', 'fcfe'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'fsa-ratios',
        topicTitle: 'Ratios and DuPont',
        cards: [
          {
            id: 'fsa-liquidity',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-ratios',
            topicTitle: 'Ratios and DuPont',
            kind: 'formula',
            front: 'Liquidity ratios',
            back: 'Current ratio = current assets / current liabilities. Quick ratio removes inventory to focus on the fastest assets.',
            hint: 'Can they pay near-term bills?',
            tags: ['liquidity', 'ratios', 'analysis'],
            difficulty: 2,
          },
          {
            id: 'fsa-solvency',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-ratios',
            topicTitle: 'Ratios and DuPont',
            kind: 'formula',
            front: 'Solvency and leverage ratios',
            back: 'Debt-to-equity, debt-to-assets, and interest coverage tell you how much permanent leverage the firm is carrying.',
            hint: 'Long-term balance sheet risk.',
            tags: ['solvency', 'leverage', 'ratios'],
            difficulty: 3,
          },
          {
            id: 'fsa-dupont',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-ratios',
            topicTitle: 'Ratios and DuPont',
            kind: 'formula',
            front: 'Traditional DuPont decomposition',
            back: 'ROE = net profit margin x asset turnover x financial leverage. It explains how profit, efficiency, and leverage drive returns.',
            hint: 'Margin x turnover x leverage.',
            tags: ['dupont', 'roe', 'ratios'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'fsa-quality',
        topicTitle: 'Accounting quality',
        cards: [
          {
            id: 'fsa-inventory-lifo',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-quality',
            topicTitle: 'Accounting quality',
            kind: 'warning',
            front: 'Why does the LIFO reserve matter?',
            back: 'It bridges LIFO to FIFO reporting and helps compare firms that use different inventory methods.',
            hint: 'It is a comparison bridge.',
            tags: ['inventory', 'lifo', 'quality'],
            difficulty: 3,
          },
          {
            id: 'fsa-tax',
            subjectId: 'financial-reporting',
            subjectTitle: 'Financial Statement Analysis',
            subjectWeight: '11-14%',
            topicId: 'fsa-quality',
            topicTitle: 'Accounting quality',
            kind: 'formula',
            front: 'Effective tax rate',
            back: 'Effective tax rate = income tax expense / pretax income. It can differ sharply from the statutory rate.',
            hint: 'Taxes actually paid in the books.',
            tags: ['tax', 'quality', 'formula'],
            difficulty: 2,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'corporate-issuers',
    subjectTitle: 'Corporate Issuers',
    subjectWeight: '6-9%',
    topics: [
      {
        topicId: 'corp-cash-flow',
        topicTitle: 'Capital budgeting and liquidity',
        cards: [
          {
            id: 'corp-npv',
            subjectId: 'corporate-issuers',
            subjectTitle: 'Corporate Issuers',
            subjectWeight: '6-9%',
            topicId: 'corp-cash-flow',
            topicTitle: 'Capital budgeting and liquidity',
            kind: 'formula',
            front: 'Net present value',
            back: 'NPV = present value of expected cash flows - initial outlay. Accept a normal project when NPV is positive.',
            hint: 'Value created today.',
            tags: ['npv', 'capital budgeting', 'formula'],
            difficulty: 3,
          },
          {
            id: 'corp-irr',
            subjectId: 'corporate-issuers',
            subjectTitle: 'Corporate Issuers',
            subjectWeight: '6-9%',
            topicId: 'corp-cash-flow',
            topicTitle: 'Capital budgeting and liquidity',
            kind: 'formula',
            front: 'Internal rate of return',
            back: 'IRR is the discount rate that makes NPV equal zero. Use it carefully when projects differ in scale or timing.',
            hint: 'The zero-NPV rate.',
            tags: ['irr', 'capital budgeting', 'formula'],
            difficulty: 3,
          },
          {
            id: 'corp-ccc',
            subjectId: 'corporate-issuers',
            subjectTitle: 'Corporate Issuers',
            subjectWeight: '6-9%',
            topicId: 'corp-cash-flow',
            topicTitle: 'Capital budgeting and liquidity',
            kind: 'formula',
            front: 'Cash conversion cycle',
            back: 'CCC = days inventory outstanding + days sales outstanding - days payables outstanding. Lower is usually better for working capital.',
            hint: 'Cash tied up in operations.',
            tags: ['working capital', 'ccc', 'formula'],
            difficulty: 3,
          },
        ],
      },
      {
        topicId: 'corp-capital',
        topicTitle: 'Cost of capital and leverage',
        cards: [
          {
            id: 'corp-wacc',
            subjectId: 'corporate-issuers',
            subjectTitle: 'Corporate Issuers',
            subjectWeight: '6-9%',
            topicId: 'corp-capital',
            topicTitle: 'Cost of capital and leverage',
            kind: 'formula',
            front: 'Weighted average cost of capital',
            back: 'WACC = wd rd(1 - tax) + wp rp + we re. Use target capital structure weights when the question asks for company-wide required return.',
            hint: 'Debt, preferred, equity.',
            tags: ['wacc', 'cost of capital', 'formula'],
            difficulty: 4,
          },
          {
            id: 'corp-roic',
            subjectId: 'corporate-issuers',
            subjectTitle: 'Corporate Issuers',
            subjectWeight: '6-9%',
            topicId: 'corp-capital',
            topicTitle: 'Cost of capital and leverage',
            kind: 'formula',
            front: 'Return on invested capital',
            back: 'ROIC = after-tax operating profit / average invested capital. If ROIC is above WACC, the firm is creating value.',
            hint: 'Compare returns to capital cost.',
            tags: ['roic', 'value creation', 'formula'],
            difficulty: 3,
          },
          {
            id: 'corp-leverage',
            subjectId: 'corporate-issuers',
            subjectTitle: 'Corporate Issuers',
            subjectWeight: '6-9%',
            topicId: 'corp-capital',
            topicTitle: 'Cost of capital and leverage',
            kind: 'formula',
            front: 'Degree of operating and financial leverage',
            back: 'Higher fixed costs raise operating leverage; more debt raises financial leverage. Combined leverage shows how sensitive EPS is to sales changes.',
            hint: 'Fixed costs amplify change.',
            tags: ['leverage', 'corporate', 'formula'],
            difficulty: 4,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'equity',
    subjectTitle: 'Equity Investments',
    subjectWeight: '11-14%',
    topics: [
      {
        topicId: 'equity-return',
        topicTitle: 'Risk and return',
        cards: [
          {
            id: 'equity-beta',
            subjectId: 'equity',
            subjectTitle: 'Equity Investments',
            subjectWeight: '11-14%',
            topicId: 'equity-return',
            topicTitle: 'Risk and return',
            kind: 'formula',
            front: 'Beta and CAPM',
            back: 'Beta measures sensitivity to market returns. CAPM says expected return = risk-free rate + beta x market risk premium.',
            hint: 'Systematic risk only.',
            tags: ['beta', 'capm', 'formula'],
            difficulty: 4,
          },
          {
            id: 'equity-valuation',
            subjectId: 'equity',
            subjectTitle: 'Equity Investments',
            subjectWeight: '11-14%',
            topicId: 'equity-return',
            topicTitle: 'Risk and return',
            kind: 'formula',
            front: 'Dividend discount model',
            back: 'Stock value equals the present value of future dividends. The Gordon model is the constant-growth version of this idea.',
            hint: 'Value = PV of dividends.',
            tags: ['ddm', 'valuation', 'formula'],
            difficulty: 3,
          },
          {
            id: 'equity-growth',
            subjectId: 'equity',
            subjectTitle: 'Equity Investments',
            subjectWeight: '11-14%',
            topicId: 'equity-return',
            topicTitle: 'Risk and return',
            kind: 'formula',
            front: 'Gordon growth model',
            back: 'P0 = D1 / (r - g). It works when dividends grow at a stable rate and r is greater than g.',
            hint: 'Constant growth version.',
            tags: ['gordon', 'growth', 'formula'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'equity-multiples',
        topicTitle: 'Valuation multiples and market indices',
        cards: [
          {
            id: 'equity-multiples-card',
            subjectId: 'equity',
            subjectTitle: 'Equity Investments',
            subjectWeight: '11-14%',
            topicId: 'equity-multiples',
            topicTitle: 'Valuation multiples and market indices',
            kind: 'formula',
            front: 'Price and enterprise value multiples',
            back: 'P/E uses equity value per share; EV/EBITDA and similar multiples compare enterprise value to operating cash flow proxies.',
            hint: 'Equity multiple vs enterprise multiple.',
            tags: ['multiples', 'valuation', 'equity'],
            difficulty: 3,
          },
          {
            id: 'equity-index',
            subjectId: 'equity',
            subjectTitle: 'Equity Investments',
            subjectWeight: '11-14%',
            topicId: 'equity-multiples',
            topicTitle: 'Valuation multiples and market indices',
            kind: 'concept',
            front: 'How do price-weighted and equal-weighted indexes differ?',
            back: 'Price-weighted indexes let high-priced stocks dominate; equal-weighted indexes give every constituent the same influence and usually need periodic rebalancing.',
            hint: 'Different weighting, different bias.',
            tags: ['index', 'weighting', 'market structure'],
            difficulty: 2,
          },
          {
            id: 'equity-return-on-equity',
            subjectId: 'equity',
            subjectTitle: 'Equity Investments',
            subjectWeight: '11-14%',
            topicId: 'equity-multiples',
            topicTitle: 'Valuation multiples and market indices',
            kind: 'formula',
            front: 'Accounting return on equity',
            back: 'Accounting ROE = net income / average common equity. It is a simple snapshot of profitability from the shareholder perspective.',
            hint: 'Bottom line over equity base.',
            tags: ['roe', 'equity', 'formula'],
            difficulty: 2,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'fixed-income',
    subjectTitle: 'Fixed Income',
    subjectWeight: '11-14%',
    topics: [
      {
        topicId: 'fi-pricing',
        topicTitle: 'Bond pricing and yield',
        cards: [
          {
            id: 'fi-price',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-pricing',
            topicTitle: 'Bond pricing and yield',
            kind: 'formula',
            front: 'Bond price',
            back: 'Bond price is the present value of coupon payments plus principal, discounted at the required yield.',
            hint: 'PV of coupons plus par.',
            tags: ['bond', 'price', 'formula'],
            difficulty: 3,
          },
          {
            id: 'fi-yield-curve',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-pricing',
            topicTitle: 'Bond pricing and yield',
            kind: 'concept',
            front: 'Why are price and yield inversely related?',
            back: 'A higher yield discounts future cash flows more heavily, which lowers price. A lower yield does the opposite.',
            hint: 'Discount rate moves price.',
            tags: ['yield', 'price', 'concept'],
            difficulty: 2,
          },
          {
            id: 'fi-spot',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-pricing',
            topicTitle: 'Bond pricing and yield',
            kind: 'formula',
            front: 'Spot-rate pricing',
            back: 'Discount each cash flow at its own spot rate instead of a single YTM. It is the cleanest no-arbitrage valuation approach.',
            hint: 'One rate per cash flow.',
            tags: ['spot rate', 'valuation', 'formula'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'fi-risk',
        topicTitle: 'Duration, convexity, and spreads',
        cards: [
          {
            id: 'fi-duration',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-risk',
            topicTitle: 'Duration, convexity, and spreads',
            kind: 'formula',
            front: 'Macaulay duration and modified duration',
            back: 'Macaulay duration is the weighted average time to receive cash flows. Modified duration = Macaulay duration / (1 + yield per period).',
            hint: 'Time weighted, then yield adjusted.',
            tags: ['duration', 'risk', 'formula'],
            difficulty: 4,
          },
          {
            id: 'fi-convexity',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-risk',
            topicTitle: 'Duration, convexity, and spreads',
            kind: 'formula',
            front: 'Why do we care about convexity?',
            back: 'Duration is a linear estimate. Convexity captures curvature and improves price estimates when yield changes are larger.',
            hint: 'The curve matters.',
            tags: ['convexity', 'price risk', 'formula'],
            difficulty: 4,
          },
          {
            id: 'fi-spread',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-risk',
            topicTitle: 'Duration, convexity, and spreads',
            kind: 'formula',
            front: 'Yield spread and OAS',
            back: 'Yield spread = liquidity premium + credit spread. OAS removes embedded option value from a spread-based estimate.',
            hint: 'Spread plus option adjustment.',
            tags: ['spread', 'oas', 'credit'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'fi-structures',
        topicTitle: 'Bond structures',
        cards: [
          {
            id: 'fi-floating',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-structures',
            topicTitle: 'Bond structures',
            kind: 'formula',
            front: 'Floating-rate note pricing intuition',
            back: 'The coupon resets with the reference index plus a quoted margin. Price stays near par when resets reflect current rates.',
            hint: 'Reset keeps price anchored.',
            tags: ['frn', 'coupon', 'formula'],
            difficulty: 3,
          },
          {
            id: 'fi-callable',
            subjectId: 'fixed-income',
            subjectTitle: 'Fixed Income',
            subjectWeight: '11-14%',
            topicId: 'fi-structures',
            topicTitle: 'Bond structures',
            kind: 'concept',
            front: 'Why do callable bonds usually yield more than straight bonds?',
            back: 'The call option benefits the issuer, so investors demand extra yield as compensation for reinvestment and truncation risk.',
            hint: 'Issuer owns the option.',
            tags: ['callable', 'option', 'yield'],
            difficulty: 3,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'derivatives',
    subjectTitle: 'Derivatives',
    subjectWeight: '5-8%',
    topics: [
      {
        topicId: 'deriv-forward',
        topicTitle: 'Forwards and futures',
        cards: [
          {
            id: 'deriv-forward-price',
            subjectId: 'derivatives',
            subjectTitle: 'Derivatives',
            subjectWeight: '5-8%',
            topicId: 'deriv-forward',
            topicTitle: 'Forwards and futures',
            kind: 'formula',
            front: 'Forward pricing intuition',
            back: 'Forward price reflects spot price adjusted for financing, carry, and any income from the underlying asset.',
            hint: 'Spot plus carry.',
            tags: ['forward', 'futures', 'formula'],
            difficulty: 4,
          },
          {
            id: 'deriv-fx-forward',
            subjectId: 'derivatives',
            subjectTitle: 'Derivatives',
            subjectWeight: '5-8%',
            topicId: 'deriv-forward',
            topicTitle: 'Forwards and futures',
            kind: 'formula',
            front: 'FX forward no-arbitrage idea',
            back: 'The forward rate reflects the interest rate differential between the two currencies. Higher domestic rates usually make the domestic currency trade at a forward discount.',
            hint: 'Rates drive FX forwards.',
            tags: ['fx', 'forward', 'arbitrage'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'deriv-options',
        topicTitle: 'Options basics',
        cards: [
          {
            id: 'deriv-payoff',
            subjectId: 'derivatives',
            subjectTitle: 'Derivatives',
            subjectWeight: '5-8%',
            topicId: 'deriv-options',
            topicTitle: 'Options basics',
            kind: 'formula',
            front: 'Call and put payoff at expiry',
            back: 'Call payoff = max(S - K, 0). Put payoff = max(K - S, 0). The option holder never has a negative intrinsic payoff.',
            hint: 'Never worse than zero.',
            tags: ['options', 'payoff', 'formula'],
            difficulty: 2,
          },
          {
            id: 'deriv-moneyness',
            subjectId: 'derivatives',
            subjectTitle: 'Derivatives',
            subjectWeight: '5-8%',
            topicId: 'deriv-options',
            topicTitle: 'Options basics',
            kind: 'concept',
            front: 'What does moneyness tell you?',
            back: 'It tells you whether exercising the option would be profitable at the current underlying price, before time value is considered.',
            hint: 'In the money or not.',
            tags: ['moneyness', 'options', 'concept'],
            difficulty: 2,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'alternative-investments',
    subjectTitle: 'Alternative Investments',
    subjectWeight: '5-8%',
    topics: [
      {
        topicId: 'alt-structures',
        topicTitle: 'Structures and fees',
        cards: [
          {
            id: 'alt-lp-gp',
            subjectId: 'alternative-investments',
            subjectTitle: 'Alternative Investments',
            subjectWeight: '5-8%',
            topicId: 'alt-structures',
            topicTitle: 'Structures and fees',
            kind: 'concept',
            front: 'How do private funds usually work?',
            back: 'They commonly use a limited partner and general partner structure, with illiquidity, capital calls, and performance fees that differ from public markets.',
            hint: 'Private capital is structured differently.',
            tags: ['private equity', 'fund structure', 'concept'],
            difficulty: 2,
          },
          {
            id: 'alt-fees',
            subjectId: 'alternative-investments',
            subjectTitle: 'Alternative Investments',
            subjectWeight: '5-8%',
            topicId: 'alt-structures',
            topicTitle: 'Structures and fees',
            kind: 'warning',
            front: 'What should you remember about alternative fees and liquidity?',
            back: 'Fees can be layered and liquidity can be restricted, so expected return must be judged together with lockups, valuation lag, and cash-flow timing.',
            hint: 'Return and liquidity go together.',
            tags: ['alternatives', 'fees', 'liquidity'],
            difficulty: 3,
          },
        ],
      },
      {
        topicId: 'alt-asset-types',
        topicTitle: 'Asset types',
        cards: [
          {
            id: 'alt-real-assets',
            subjectId: 'alternative-investments',
            subjectTitle: 'Alternative Investments',
            subjectWeight: '5-8%',
            topicId: 'alt-asset-types',
            topicTitle: 'Asset types',
            kind: 'concept',
            front: 'What makes real assets different?',
            back: 'They are tied to physical or tangible assets such as property, infrastructure, or commodities and often have inflation-hedging characteristics.',
            hint: 'Tangible and often inflation linked.',
            tags: ['real assets', 'property', 'concept'],
            difficulty: 2,
          },
        ],
      },
    ],
  },
  {
    subjectId: 'portfolio-management',
    subjectTitle: 'Portfolio Management',
    subjectWeight: '8-12%',
    topics: [
      {
        topicId: 'pm-risk-return',
        topicTitle: 'Risk and return',
        cards: [
          {
            id: 'pm-expected-return',
            subjectId: 'portfolio-management',
            subjectTitle: 'Portfolio Management',
            subjectWeight: '8-12%',
            topicId: 'pm-risk-return',
            topicTitle: 'Risk and return',
            kind: 'formula',
            front: 'Expected return on a portfolio',
            back: 'Expected portfolio return is the weighted average of the expected returns on the assets in the portfolio.',
            hint: 'Weights times expected returns.',
            tags: ['portfolio', 'expected return', 'formula'],
            difficulty: 2,
          },
          {
            id: 'pm-sharpe',
            subjectId: 'portfolio-management',
            subjectTitle: 'Portfolio Management',
            subjectWeight: '8-12%',
            topicId: 'pm-risk-return',
            topicTitle: 'Risk and return',
            kind: 'formula',
            front: 'Sharpe ratio',
            back: 'Sharpe = (portfolio return - risk-free rate) / portfolio standard deviation. It rewards excess return per unit of total risk.',
            hint: 'Return per unit of total risk.',
            tags: ['sharpe', 'performance', 'formula'],
            difficulty: 3,
          },
          {
            id: 'pm-treynor',
            subjectId: 'portfolio-management',
            subjectTitle: 'Portfolio Management',
            subjectWeight: '8-12%',
            topicId: 'pm-risk-return',
            topicTitle: 'Risk and return',
            kind: 'formula',
            front: 'Treynor ratio and Jensen alpha',
            back: 'Treynor uses beta instead of total risk. Jensen alpha measures return above or below the CAPM benchmark.',
            hint: 'Beta-based performance.',
            tags: ['treynor', 'jensen', 'formula'],
            difficulty: 4,
          },
        ],
      },
      {
        topicId: 'pm-variance',
        topicTitle: 'Portfolio construction',
        cards: [
          {
            id: 'pm-variance',
            subjectId: 'portfolio-management',
            subjectTitle: 'Portfolio Management',
            subjectWeight: '8-12%',
            topicId: 'pm-variance',
            topicTitle: 'Portfolio construction',
            kind: 'formula',
            front: 'Portfolio variance',
            back: 'Portfolio variance depends on weights, individual variances, and covariance. Diversification works best when correlations are less than +1.',
            hint: 'Correlation controls diversification.',
            tags: ['variance', 'diversification', 'formula'],
            difficulty: 4,
          },
          {
            id: 'pm-capm-line',
            subjectId: 'portfolio-management',
            subjectTitle: 'Portfolio Management',
            subjectWeight: '8-12%',
            topicId: 'pm-variance',
            topicTitle: 'Portfolio construction',
            kind: 'concept',
            front: 'What is the capital market line?',
            back: 'It shows the risk-return tradeoff for efficient portfolios formed by combining the risk-free asset and the optimal risky portfolio.',
            hint: 'Risk-free plus tangency portfolio.',
            tags: ['cml', 'efficient frontier', 'concept'],
            difficulty: 3,
          },
        ],
      },
    ],
  },
]

export const flashcardCatalogue = syllabusFlashcards

export const flashcardsDeck = syllabusFlashcards.flatMap((subject) =>
  subject.topics.flatMap((topic) =>
    topic.cards.map((card) => ({
      ...card,
      subject,
      topic,
    })),
  ),
)

