export const formulaHeavySubjects = [
  'Quantitative Methods',
  'Economics',
  'Corporate Issuers',
  'Financial Statement Analysis',
  'Equity Investments',
  'Fixed Income',
  'Derivatives',
  'Alternative Investments',
  'Portfolio Management',
] as const

export type FormulaHeavySubject = (typeof formulaHeavySubjects)[number]

export type RevisionNote = {
  id: string
  subject: FormulaHeavySubject
  module: string
  concept: string
  terms: string[]
  formulas: string[]
  trap: string
  quickRecall: string
  tags: string[]
}

export type CalculatorDrill = {
  id: string
  subject: FormulaHeavySubject
  module: string
  skill: string
  question: string
  expectedAnswer: string
  numericAnswer: number
  tolerance: number
  baIIPlusKeystrokes: string[]
  trick: string
  explanation: string
  tags: string[]
  difficulty: 'easy' | 'medium' | 'hard'
}

export const revisionNotes: RevisionNote[] = [
  {
    id: 'quant-rates-return-stack',
    subject: 'Quantitative Methods',
    module: 'Rates and Returns',
    concept: 'Return questions usually ask whether the return is holding-period, arithmetic average, geometric average, money-weighted, time-weighted, nominal, real, gross, or net.',
    terms: ['holding period return', 'arithmetic mean', 'geometric mean', 'money-weighted return', 'time-weighted return', 'real return'],
    formulas: [
      'HPR = (ending value - beginning value + income) / beginning value',
      'geometric mean = [(1 + R1)(1 + R2)...(1 + Rn)]^(1/n) - 1',
      'real return approximately = nominal return - inflation',
      'real return exactly = (1 + nominal return) / (1 + inflation) - 1',
    ],
    trap: 'Arithmetic mean is best for a one-period expected return; geometric mean is best for multi-period compound performance.',
    quickRecall: 'If returns compound across time, multiply growth factors first.',
    tags: ['return', 'compounding', 'formula'],
  },
  {
    id: 'quant-tvm-signs',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    concept: 'TVM problems are cash-flow timeline problems. The BA II Plus needs cash inflows and outflows entered with opposite signs.',
    terms: ['PV', 'FV', 'PMT', 'N', 'I/Y', 'annuity due', 'ordinary annuity'],
    formulas: [
      'FV = PV(1 + r)^N',
      'PV = FV / (1 + r)^N',
      'PV perpetuity = PMT / r',
      'EAR = (1 + periodic rate)^m - 1',
    ],
    trap: 'Leaving old TVM values in the calculator is a silent killer. Clear TVM before every fresh TVM problem.',
    quickRecall: 'Money paid out is negative; money received is positive.',
    tags: ['tvm', 'calculator', 'formula'],
  },
  {
    id: 'quant-statistics-risk',
    subject: 'Quantitative Methods',
    module: 'Statistical Measures of Asset Returns',
    concept: 'Dispersion measures how spread out returns are. CFA questions often move between variance, standard deviation, coefficient of variation, and downside risk.',
    terms: ['variance', 'standard deviation', 'coefficient of variation', 'skewness', 'kurtosis'],
    formulas: [
      'sample variance = sum[(Xi - mean)^2] / (n - 1)',
      'standard deviation = square root of variance',
      'coefficient of variation = standard deviation / mean return',
    ],
    trap: 'The BA II Plus sample standard deviation is Sx. Population standard deviation is sigma x. CFA samples usually use Sx unless stated otherwise.',
    quickRecall: 'Variance is squared risk; standard deviation brings risk back into return units.',
    tags: ['statistics', 'risk', 'calculator'],
  },
  {
    id: 'quant-probability-hypothesis',
    subject: 'Quantitative Methods',
    module: 'Probability, Estimation, and Hypothesis Testing',
    concept: 'Probability and testing questions reward setup more than arithmetic. Identify the condition, the sample statistic, the standard error, and the rejection rule.',
    terms: ['conditional probability', 'Bayes', 'standard error', 'confidence interval', 'p-value', 'Type I error', 'Type II error'],
    formulas: [
      'P(A|B) = P(B|A)P(A) / P(B)',
      'confidence interval = point estimate +/- reliability factor x standard error',
      't-statistic = (sample statistic - hypothesized value) / standard error',
    ],
    trap: 'A small p-value means reject the null; it does not prove the alternative is economically important.',
    quickRecall: 'Type I is rejecting a true null; Type II is failing to reject a false null.',
    tags: ['probability', 'hypothesis-testing', 'formula'],
  },
  {
    id: 'economics-fx-cross-rates',
    subject: 'Economics',
    module: 'Exchange Rate Calculations',
    concept: 'FX questions are quote-direction questions. Write the currency units before calculating so numerator and denominator cancel cleanly.',
    terms: ['base currency', 'price currency', 'direct quote', 'indirect quote', 'cross rate', 'forward points'],
    formulas: [
      'real exchange rate = nominal exchange rate x domestic price / foreign price',
      'forward premium or discount approximately = forward rate / spot rate - 1',
      'cross rate = quote 1 x quote 2 when middle currency cancels',
    ],
    trap: 'If the answer is inverted, the number may look reasonable but the quote direction is wrong.',
    quickRecall: 'Treat FX like unit conversion and cancel currencies on paper.',
    tags: ['fx', 'macro', 'formula'],
  },
  {
    id: 'economics-fiscal-multiplier',
    subject: 'Economics',
    module: 'Fiscal Policy',
    concept: 'Fiscal multiplier questions connect marginal propensity to consume with the total change in output from a spending shock.',
    terms: ['MPC', 'MPS', 'fiscal multiplier', 'tax multiplier', 'automatic stabilizer'],
    formulas: ['spending multiplier = 1 / (1 - MPC)', 'tax multiplier = -MPC / (1 - MPC)', 'MPS = 1 - MPC'],
    trap: 'Tax multipliers are smaller in absolute value than spending multipliers because households save part of the tax cut.',
    quickRecall: 'Higher MPC means a larger ripple through GDP.',
    tags: ['fiscal-policy', 'multiplier', 'formula'],
  },
  {
    id: 'corp-capital-budgeting',
    subject: 'Corporate Issuers',
    module: 'Capital Investments and Capital Allocation',
    concept: 'Capital budgeting compares project cash flows against the opportunity cost of capital.',
    terms: ['NPV', 'IRR', 'payback period', 'profitability index', 'mutually exclusive projects'],
    formulas: ['NPV = PV inflows - initial outlay', 'profitability index = PV future cash flows / initial investment', 'IRR is the discount rate that sets NPV to zero'],
    trap: 'For mutually exclusive projects, choose the higher NPV, not necessarily the higher IRR.',
    quickRecall: 'NPV directly measures value added.',
    tags: ['npv', 'irr', 'cash-flow', 'formula'],
  },
  {
    id: 'corp-working-capital',
    subject: 'Corporate Issuers',
    module: 'Working Capital and Liquidity',
    concept: 'Working capital ratios explain how quickly a company turns inventory and receivables into cash while using supplier financing.',
    terms: ['DIO', 'DSO', 'DPO', 'cash conversion cycle', 'current ratio', 'quick ratio'],
    formulas: [
      'cash conversion cycle = DIO + DSO - DPO',
      'current ratio = current assets / current liabilities',
      'quick ratio = (cash + marketable securities + receivables) / current liabilities',
    ],
    trap: 'A longer DPO can improve the cash conversion cycle, but stretching suppliers can create operating risk.',
    quickRecall: 'Inventory days plus collection days minus supplier float.',
    tags: ['liquidity', 'working-capital', 'formula'],
  },
  {
    id: 'corp-wacc-leverage',
    subject: 'Corporate Issuers',
    module: 'Capital Structure',
    concept: 'WACC blends required returns by capital weight and uses after-tax cost of debt because interest is tax deductible.',
    terms: ['WACC', 'cost of debt', 'cost of equity', 'target weights', 'financial leverage'],
    formulas: ['WACC = wd rd(1 - tax rate) + wp rp + we re', 'degree of financial leverage = EBIT / (EBIT - interest)'],
    trap: 'Use market value weights when available, not book weights.',
    quickRecall: 'Debt gets the tax shield; equity does not.',
    tags: ['wacc', 'leverage', 'formula'],
  },
  {
    id: 'fsa-income-ratios',
    subject: 'Financial Statement Analysis',
    module: 'Analyzing Income Statements',
    concept: 'Income statement analysis separates profitability, operating efficiency, and capital structure effects.',
    terms: ['gross margin', 'operating margin', 'net margin', 'basic EPS', 'diluted EPS'],
    formulas: [
      'gross margin = gross profit / revenue',
      'operating margin = operating income / revenue',
      'net margin = net income / revenue',
      'basic EPS = (net income - preferred dividends) / weighted average common shares',
    ],
    trap: 'Diluted EPS includes potential common shares only if they reduce EPS.',
    quickRecall: 'Margins are scaled by revenue; EPS is scaled by shares.',
    tags: ['income-statement', 'eps', 'formula'],
  },
  {
    id: 'fsa-cash-flow-quality',
    subject: 'Financial Statement Analysis',
    module: 'Analyzing Statements of Cash Flows',
    concept: 'Cash flow analysis checks whether earnings are converting into operating cash and whether growth is internally funded.',
    terms: ['CFO', 'CFI', 'CFF', 'free cash flow to firm', 'free cash flow to equity'],
    formulas: [
      'FCFF = NI + NCC + interest expense(1 - tax rate) - fixed capital investment - working capital investment',
      'FCFE = CFO - fixed capital investment + net borrowing',
      'cash flow performance ratio = CFO / revenue',
    ],
    trap: 'Under IFRS, interest and dividends can be classified differently, so compare classifications before comparing companies.',
    quickRecall: 'FCFF belongs to all capital providers; FCFE belongs to common equity.',
    tags: ['cash-flow', 'fcff', 'fcfe', 'formula'],
  },
  {
    id: 'fsa-inventory-depreciation',
    subject: 'Financial Statement Analysis',
    module: 'Inventories and Long-Term Assets',
    concept: 'Inventory and depreciation methods affect COGS, assets, income, ratios, and taxes.',
    terms: ['FIFO', 'LIFO', 'weighted average cost', 'straight-line depreciation', 'accelerated depreciation'],
    formulas: [
      'COGS = beginning inventory + purchases - ending inventory',
      'straight-line depreciation = (cost - salvage value) / useful life',
      'average age = accumulated depreciation / annual depreciation expense',
    ],
    trap: 'In rising prices, FIFO usually reports lower COGS, higher income, higher inventory, and higher taxes than LIFO.',
    quickRecall: 'FIFO ending inventory is closer to current replacement cost.',
    tags: ['inventory', 'depreciation', 'formula'],
  },
  {
    id: 'fsa-dupont',
    subject: 'Financial Statement Analysis',
    module: 'Financial Analysis Techniques',
    concept: 'DuPont analysis decomposes ROE into profitability, efficiency, and leverage drivers.',
    terms: ['ROE', 'ROA', 'asset turnover', 'financial leverage', 'tax burden', 'interest burden'],
    formulas: [
      'ROE = net income / average equity',
      'three-part DuPont ROE = net margin x asset turnover x financial leverage',
      'financial leverage = average assets / average equity',
    ],
    trap: 'Higher ROE from leverage is not automatically better because risk may have increased.',
    quickRecall: 'Margin x turnover x leverage explains ROE.',
    tags: ['dupont', 'ratios', 'formula'],
  },
  {
    id: 'equity-ddm-gordon',
    subject: 'Equity Investments',
    module: 'Equity Valuation: Concepts and Basic Tools',
    concept: 'Dividend discount models value equity as the present value of expected dividends.',
    terms: ['DDM', 'Gordon growth model', 'required return', 'sustainable growth', 'retention ratio'],
    formulas: ['V0 = D1 / (r - g)', 'g = retention ratio x ROE', 'justified P/E = payout ratio / (r - g)'],
    trap: 'The Gordon model only works when r is greater than g and growth is stable.',
    quickRecall: 'Next dividend over required return minus growth.',
    tags: ['equity', 'ddm', 'formula'],
  },
  {
    id: 'equity-indexes-multiples',
    subject: 'Equity Investments',
    module: 'Security Market Indexes and Valuation Multiples',
    concept: 'Index and multiple questions test construction mechanics and whether a ratio is justified by fundamentals.',
    terms: ['price-weighted index', 'market-cap-weighted index', 'equal-weighted index', 'P/E', 'P/B', 'EV/EBITDA'],
    formulas: ['price return = (ending price - beginning price) / beginning price', 'total return = price return + income return', 'justified P/B = (ROE - g) / (r - g)'],
    trap: 'A high multiple can be justified by higher growth, lower risk, or higher profitability, not just overvaluation.',
    quickRecall: 'Compare multiples only after checking growth, risk, and accounting quality.',
    tags: ['indexes', 'multiples', 'formula'],
  },
  {
    id: 'fixed-income-bond-price',
    subject: 'Fixed Income',
    module: 'Fixed-Income Bond Valuation: Prices and Yields',
    concept: 'A bond price is the present value of coupon cash flows plus principal, discounted at the yield per period.',
    terms: ['coupon rate', 'yield to maturity', 'discount bond', 'premium bond', 'par value', 'current yield'],
    formulas: ['bond price = PV coupons + PV par value', 'current yield = annual coupon / full price', 'periodic yield = annual yield / payments per year'],
    trap: 'Match N, I/Y, and PMT to the coupon frequency. Semiannual bonds double N and halve the annual coupon and yield.',
    quickRecall: 'Coupon rate sets PMT; market yield discounts PMT and FV.',
    tags: ['bond', 'yield', 'calculator'],
  },
  {
    id: 'fixed-income-duration-convexity',
    subject: 'Fixed Income',
    module: 'Interest Rate Risk and Return',
    concept: 'Duration approximates the price impact of a yield change; convexity improves the estimate for larger yield moves.',
    terms: ['Macaulay duration', 'modified duration', 'effective duration', 'convexity', 'basis point'],
    formulas: [
      'approximate % price change = -modified duration x change in yield',
      'duration plus convexity estimate = -duration x delta y + 0.5 x convexity x delta y^2',
    ],
    trap: 'Use yield change in decimal form. A 50 bp increase is 0.005, not 0.50.',
    quickRecall: 'Rates up, bond prices down; convexity softens the damage.',
    tags: ['duration', 'convexity', 'formula'],
  },
  {
    id: 'fixed-income-spot-forward',
    subject: 'Fixed Income',
    module: 'The Term Structure of Interest Rates',
    concept: 'Spot rates discount single future cash flows; forward rates are implied future rates that make no-arbitrage pricing hold.',
    terms: ['spot rate', 'forward rate', 'par rate', 'yield curve', 'bootstrapping'],
    formulas: ['(1 + z2)^2 = (1 + z1)(1 + 1f1)', 'PV cash flow = CF / (1 + spot rate)^period'],
    trap: 'Do not use one YTM to discount every cash flow when the question gives spot rates.',
    quickRecall: 'Each cash flow gets its own spot rate.',
    tags: ['spot-rate', 'forward-rate', 'formula'],
  },
  {
    id: 'derivatives-forwards-carry',
    subject: 'Derivatives',
    module: 'Arbitrage, Replication, and Cost of Carry',
    concept: 'Forward pricing is a no-arbitrage carry problem: start with spot, add financing/storage costs, subtract benefits.',
    terms: ['forward price', 'cost of carry', 'convenience yield', 'arbitrage', 'replication'],
    formulas: ['forward price approximately = spot price x (1 + risk-free rate)^T + costs - benefits', 'with continuous compounding: F0 = S0 e^((r + costs - yield)T)'],
    trap: 'Benefits from holding the asset reduce the forward price; costs increase it.',
    quickRecall: 'Carry costs up, asset benefits down.',
    tags: ['forwards', 'cost-of-carry', 'formula'],
  },
  {
    id: 'derivatives-options-parity',
    subject: 'Derivatives',
    module: 'Option Replication Using Put-Call Parity',
    concept: 'Put-call parity links a fiduciary call and a protective put for European options on non-dividend-paying stock.',
    terms: ['call option', 'put option', 'fiduciary call', 'protective put', 'exercise price'],
    formulas: ['C + PV(X) = P + S0', 'C - P = S0 - PV(X)'],
    trap: 'Parity is for European options. Early exercise features can break strict equality for American options.',
    quickRecall: 'Call plus safe bond equals put plus stock.',
    tags: ['options', 'put-call-parity', 'formula'],
  },
  {
    id: 'derivatives-binomial',
    subject: 'Derivatives',
    module: 'Valuing a Derivative Using a One-Period Binomial Model',
    concept: 'The one-period binomial model values an option by risk-neutral expected payoff discounted at the risk-free rate.',
    terms: ['up factor', 'down factor', 'risk-neutral probability', 'replication', 'option payoff'],
    formulas: ['risk-neutral probability = (1 + r - d) / (u - d)', 'call payoff = max(0, stock price - exercise price)', 'option value = discounted expected payoff'],
    trap: 'Use terminal stock prices for payoff first, then discount the expected option payoff.',
    quickRecall: 'Payoff at the end, probability-weight, discount back.',
    tags: ['binomial', 'options', 'formula'],
  },
  {
    id: 'alts-performance-returns',
    subject: 'Alternative Investments',
    module: 'Alternative Investment Performance and Returns',
    concept: 'Alternative investment returns often use money-weighted measures because cash flows are controlled by fund managers rather than investors.',
    terms: ['IRR', 'MOIC', 'DPI', 'RVPI', 'TVPI', 'management fee', 'carried interest'],
    formulas: ['MOIC = total value / paid-in capital', 'DPI = cumulative distributions / paid-in capital', 'RVPI = residual value / paid-in capital', 'TVPI = DPI + RVPI'],
    trap: 'A high TVPI with low DPI may still depend heavily on unrealized valuations.',
    quickRecall: 'DPI is cash back; RVPI is still on paper.',
    tags: ['alternative-investments', 'private-capital', 'formula'],
  },
  {
    id: 'portfolio-risk-return',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return',
    concept: 'Portfolio risk depends on weights, asset volatilities, and correlations, not just weighted-average individual risks.',
    terms: ['expected return', 'variance', 'standard deviation', 'correlation', 'diversification'],
    formulas: [
      'E(Rp) = sum wi E(Ri)',
      'two-asset variance = w1^2 sigma1^2 + w2^2 sigma2^2 + 2w1w2rho12sigma1sigma2',
      'CAPM: E(Ri) = Rf + betai[E(Rm) - Rf]',
    ],
    trap: 'Portfolio expected return is weighted average; portfolio standard deviation is not.',
    quickRecall: 'Correlation drives diversification benefit.',
    tags: ['portfolio', 'capm', 'formula'],
  },
  {
    id: 'portfolio-performance',
    subject: 'Portfolio Management',
    module: 'Portfolio Performance Measures',
    concept: 'Risk-adjusted performance measures divide excess return by the relevant risk measure.',
    terms: ['Sharpe ratio', 'Treynor ratio', 'Jensen alpha', 'M-squared', 'tracking error'],
    formulas: ['Sharpe ratio = (Rp - Rf) / standard deviation of portfolio', 'Treynor ratio = (Rp - Rf) / beta', 'Jensen alpha = Rp - [Rf + beta(Rm - Rf)]'],
    trap: 'Use Sharpe for total risk and Treynor or Jensen alpha for systematic risk.',
    quickRecall: 'Sharpe uses sigma; Treynor uses beta.',
    tags: ['performance', 'risk-adjusted-return', 'formula'],
  },
]

export const calculatorDrills: CalculatorDrill[] = [
  {
    id: 'calc-tvm-fv-single',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    skill: 'TVM future value',
    question: 'You invest 12,500 for 5 years at 7.2% compounded annually. What is the future value?',
    expectedAnswer: '17,696.36',
    numericAnswer: 17696.36,
    tolerance: 0.1,
    baIIPlusKeystrokes: ['2ND CLR TVM', '5 N', '7.2 I/Y', '12500 +/- PV', '0 PMT', 'CPT FV'],
    trick: 'Always clear TVM and enter the investment as negative PV so the computed FV is positive.',
    explanation: 'The calculator compounds 12,500 at 7.2% for five annual periods.',
    tags: ['tvm', 'future-value'],
    difficulty: 'easy',
  },
  {
    id: 'calc-tvm-annuity-pv',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    skill: 'Annuity present value',
    question: 'A bond-like cash flow pays 850 at the end of each year for 6 years. If the discount rate is 8%, what is the present value?',
    expectedAnswer: '3,929.45',
    numericAnswer: 3929.45,
    tolerance: 0.1,
    baIIPlusKeystrokes: ['2ND CLR TVM', '6 N', '8 I/Y', '850 PMT', '0 FV', 'CPT PV'],
    trick: 'Ordinary annuity means END mode. Keep PMT positive and read PV as the opposite sign.',
    explanation: 'The PV is the discounted value of six equal year-end payments.',
    tags: ['tvm', 'annuity'],
    difficulty: 'easy',
  },
  {
    id: 'calc-interest-ear',
    subject: 'Quantitative Methods',
    module: 'Rates and Returns',
    skill: 'Interest conversion',
    question: 'A stated annual rate is 9% compounded monthly. What is the effective annual rate?',
    expectedAnswer: '9.38%',
    numericAnswer: 9.38,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['2ND ICONV', '9 NOM', '12 C/Y', 'CPT EFF'],
    trick: 'Use ICONV instead of typing the exponent formula when compounding frequency is given.',
    explanation: 'Monthly compounding turns the 9% nominal rate into an effective rate of about 9.38%.',
    tags: ['interest-conversion', 'ear'],
    difficulty: 'easy',
  },
  {
    id: 'calc-cashflow-npv',
    subject: 'Corporate Issuers',
    module: 'Capital Investments and Capital Allocation',
    skill: 'Uneven cash flow NPV',
    question: 'A project costs 40,000 today and produces 12,000, 14,000, 16,000, and 18,000 over the next four years. At 10%, what is NPV?',
    expectedAnswer: '6,794.62',
    numericAnswer: 6794.62,
    tolerance: 0.2,
    baIIPlusKeystrokes: ['CF', '2ND CLR WORK', '40000 +/- ENTER', 'DOWN', '12000 ENTER', 'DOWN DOWN', '14000 ENTER', 'DOWN DOWN', '16000 ENTER', 'DOWN DOWN', '18000 ENTER', 'NPV', '10 ENTER', 'DOWN', 'CPT'],
    trick: 'In the CF worksheet, use frequency 1 by pressing DOWN twice after each cash flow.',
    explanation: 'Discounting the four inflows at 10% gives a present value above the 40,000 outlay.',
    tags: ['npv', 'cash-flow'],
    difficulty: 'medium',
  },
  {
    id: 'calc-cashflow-irr',
    subject: 'Corporate Issuers',
    module: 'Capital Investments and Capital Allocation',
    skill: 'IRR',
    question: 'A project costs 25,000 today and returns 8,000 per year for 4 years. What is the IRR?',
    expectedAnswer: '10.66%',
    numericAnswer: 10.66,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['CF', '2ND CLR WORK', '25000 +/- ENTER', 'DOWN', '8000 ENTER', 'DOWN', '4 ENTER', 'IRR', 'CPT'],
    trick: 'Use the frequency field for repeated equal cash flows instead of entering 8,000 four times.',
    explanation: 'The IRR is the discount rate that makes the four 8,000 inflows equal the 25,000 outlay.',
    tags: ['irr', 'cash-flow'],
    difficulty: 'medium',
  },
  {
    id: 'calc-bond-price',
    subject: 'Fixed Income',
    module: 'Fixed-Income Bond Valuation: Prices and Yields',
    skill: 'Bond price',
    question: 'A 6% annual coupon bond has 8 years to maturity, pays semiannually, and has a YTM of 7%. What is the price per 100 par?',
    expectedAnswer: '93.95',
    numericAnswer: 93.95,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['2ND CLR TVM', '16 N', '3.5 I/Y', '3 PMT', '100 FV', 'CPT PV'],
    trick: 'For semiannual bonds, double N and halve both coupon and yield.',
    explanation: 'The bond is priced below par because its 6% coupon is below the 7% market yield.',
    tags: ['bond', 'price', 'yield'],
    difficulty: 'medium',
  },
  {
    id: 'calc-bond-ytm',
    subject: 'Fixed Income',
    module: 'Fixed-Income Bond Valuation: Prices and Yields',
    skill: 'Yield to maturity',
    question: 'A 5% annual coupon bond with 10 years to maturity sells for 92.50 per 100 par. Coupons are paid semiannually. What is the annual YTM?',
    expectedAnswer: '6.01%',
    numericAnswer: 6.01,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['2ND CLR TVM', '20 N', '92.5 +/- PV', '2.5 PMT', '100 FV', 'CPT I/Y', 'x 2'],
    trick: 'CPT I/Y gives the semiannual yield. Multiply by 2 for the bond-equivalent annual yield.',
    explanation: 'The discount price raises the yield above the 5% coupon rate.',
    tags: ['bond', 'ytm'],
    difficulty: 'medium',
  },
  {
    id: 'calc-stat-sx',
    subject: 'Quantitative Methods',
    module: 'Statistical Measures of Asset Returns',
    skill: 'Sample standard deviation',
    question: 'Returns are 4%, 7%, -2%, 9%, and 6%. What is the sample standard deviation?',
    expectedAnswer: '4.21%',
    numericAnswer: 4.21,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['2ND DATA', '2ND CLR WORK', '4 ENTER DOWN DOWN', '7 ENTER DOWN DOWN', '2 +/- ENTER DOWN DOWN', '9 ENTER DOWN DOWN', '6 ENTER', '2ND STAT', 'DOWN until Sx'],
    trick: 'For one-variable stats, keep each frequency at 1 and read Sx for sample standard deviation.',
    explanation: 'The sample standard deviation of the five returns is about 4.18 percentage points.',
    tags: ['statistics', 'standard-deviation'],
    difficulty: 'medium',
  },
  {
    id: 'calc-depreciation-straight-line',
    subject: 'Financial Statement Analysis',
    module: 'Inventories and Long-Term Assets',
    skill: 'Straight-line depreciation',
    question: 'Equipment costs 78,000, has a 6,000 salvage value, and a 9-year useful life. What is annual straight-line depreciation?',
    expectedAnswer: '8,000.00',
    numericAnswer: 8000,
    tolerance: 0.1,
    baIIPlusKeystrokes: ['78000 - 6000 =', '/ 9 ='],
    trick: 'For straight-line depreciation, direct arithmetic is faster than opening the depreciation worksheet.',
    explanation: 'Depreciable cost is 72,000, spread evenly over 9 years.',
    tags: ['depreciation', 'fsa'],
    difficulty: 'easy',
  },
  {
    id: 'calc-dupont-roe',
    subject: 'Financial Statement Analysis',
    module: 'Financial Analysis Techniques',
    skill: 'DuPont ROE',
    question: 'Net margin is 8.5%, asset turnover is 1.35, and financial leverage is 2.1. What is ROE?',
    expectedAnswer: '24.10%',
    numericAnswer: 24.1,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['8.5 x 1.35 x 2.1 ='],
    trick: 'Keep ratios in percent form only at the end: 8.5 x 1.35 x 2.1 gives percent ROE directly.',
    explanation: 'Three-part DuPont multiplies profitability, efficiency, and leverage.',
    tags: ['dupont', 'roe'],
    difficulty: 'easy',
  },
  {
    id: 'calc-fx-cross-rate',
    subject: 'Economics',
    module: 'Exchange Rate Calculations',
    skill: 'Cross rate',
    question: 'Given USD/EUR = 1.08 and USD/GBP = 1.26, what is EUR/GBP?',
    expectedAnswer: '1.1667',
    numericAnswer: 1.1667,
    tolerance: 0.0005,
    baIIPlusKeystrokes: ['1.26 / 1.08 ='],
    trick: 'Write GBP in the denominator target. USD/GBP divided by USD/EUR cancels USD and gives EUR/GBP.',
    explanation: 'One GBP costs 1.26 USD and one EUR costs 1.08 USD, so one GBP costs 1.1667 EUR.',
    tags: ['fx', 'cross-rate'],
    difficulty: 'medium',
  },
  {
    id: 'calc-duration-price-change',
    subject: 'Fixed Income',
    module: 'Interest Rate Risk and Return',
    skill: 'Duration price estimate',
    question: 'A bond has modified duration 6.4. Yield rises by 35 bps. Approximate the percentage price change.',
    expectedAnswer: '-2.24%',
    numericAnswer: -2.24,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['6.4 x .0035 x 100 +/- ='],
    trick: 'Convert basis points to decimal yield first: 35 bps = 0.0035.',
    explanation: 'Approximate price change equals negative duration times the yield change.',
    tags: ['duration', 'fixed-income'],
    difficulty: 'easy',
  },
  {
    id: 'calc-convexity-adjusted',
    subject: 'Fixed Income',
    module: 'Yield-Based Bond Convexity Measures',
    skill: 'Duration plus convexity',
    question: 'Modified duration is 7.1, convexity is 68, and yield falls by 60 bps. Estimate the percentage price change with convexity.',
    expectedAnswer: '4.38%',
    numericAnswer: 4.38,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['7.1 x .006 =', '68 x .006 x .006 x .5 =', 'add both', 'x 100'],
    trick: 'For a yield decrease, the duration effect is positive. The convexity term is positive for both rate directions.',
    explanation: 'Duration adds about 4.26%; convexity adds about 0.12%, for roughly 4.38%.',
    tags: ['convexity', 'fixed-income'],
    difficulty: 'hard',
  },
  {
    id: 'calc-put-call-parity',
    subject: 'Derivatives',
    module: 'Option Replication Using Put-Call Parity',
    skill: 'Put-call parity',
    question: 'A stock is 48, the European call is 5.20, the exercise price is 50, and PV(X) is 47.15. What is the European put price?',
    expectedAnswer: '4.35',
    numericAnswer: 4.35,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['5.20 + 47.15 - 48 ='],
    trick: 'Rearrange C + PV(X) = P + S as P = C + PV(X) - S.',
    explanation: 'The protective put side must equal the fiduciary call side.',
    tags: ['options', 'put-call-parity'],
    difficulty: 'medium',
  },
  {
    id: 'calc-forward-price',
    subject: 'Derivatives',
    module: 'Arbitrage, Replication, and Cost of Carry',
    skill: 'Forward price',
    question: 'Spot is 72, the annual risk-free rate is 5%, and maturity is 9 months. Ignore income and storage. What is the no-arbitrage forward price using annual compounding?',
    expectedAnswer: '74.68',
    numericAnswer: 74.68,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['1.05 yx .75 =', 'x 72 ='],
    trick: 'Nine months is 0.75 years. Use yx for fractional exponents.',
    explanation: 'The forward price grows spot at the risk-free rate for 0.75 years.',
    tags: ['forwards', 'cost-of-carry'],
    difficulty: 'medium',
  },
  {
    id: 'calc-alt-tvpi',
    subject: 'Alternative Investments',
    module: 'Alternative Investment Performance and Returns',
    skill: 'Private capital multiples',
    question: 'Paid-in capital is 80 million, cumulative distributions are 44 million, and residual value is 68 million. What is TVPI?',
    expectedAnswer: '1.40x',
    numericAnswer: 1.4,
    tolerance: 0.01,
    baIIPlusKeystrokes: ['44 + 68 =', '/ 80 ='],
    trick: 'TVPI combines realized value and remaining value before dividing by paid-in capital.',
    explanation: 'DPI is 0.55x and RVPI is 0.85x, so TVPI is 1.40x.',
    tags: ['alternatives', 'private-capital'],
    difficulty: 'easy',
  },
  {
    id: 'calc-portfolio-variance',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return',
    skill: 'Two-asset portfolio risk',
    question: 'A portfolio is 60% in Asset A with 18% volatility and 40% in Asset B with 11% volatility. Correlation is 0.25. What is portfolio standard deviation?',
    expectedAnswer: '12.64%',
    numericAnswer: 12.64,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['.6 x .6 x .18 x .18 =', 'store or note', '.4 x .4 x .11 x .11 =', 'add', '2 x .6 x .4 x .25 x .18 x .11 =', 'add', '2ND x2 to square root', 'x 100'],
    trick: 'Use decimals for weights and volatilities, then multiply the final square root by 100.',
    explanation: 'The covariance term is positive because correlation is positive, but diversification still lowers risk below the weighted average volatility.',
    tags: ['portfolio', 'variance'],
    difficulty: 'hard',
  },
  {
    id: 'calc-capm-required-return',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return',
    skill: 'CAPM required return',
    question: 'The risk-free rate is 3.8%, expected market return is 9.5%, and beta is 1.25. What is the required return?',
    expectedAnswer: '10.93%',
    numericAnswer: 10.93,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['9.5 - 3.8 =', 'x 1.25 =', '+ 3.8 ='],
    trick: 'Compute the market risk premium first, then multiply by beta.',
    explanation: 'CAPM adds beta-adjusted market risk premium to the risk-free rate.',
    tags: ['capm', 'required-return'],
    difficulty: 'easy',
  },
]

export const calculatorSkills = Array.from(new Set(calculatorDrills.map((drill) => drill.skill)))
