export type CalculatorDrill = {
  id: string
  subject: string
  module: string
  skill: string
  question: string
  expectedAnswer: string
  numericAnswer: number
  tolerance: number
  baIIPlusKeystrokes: string[]
  trick: string
  explanation: string
  tags: string[]
  difficulty: 'easy' | 'medium' | 'hard'
}


export const calculatorDrills: CalculatorDrill[] = [
  {
    id: 'calc-tvm-fv-single',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    skill: 'TVM future value',
    question: 'You invest 12,500 for 5 years at 7.2% compounded annually. What is the future value?',
    expectedAnswer: '17,696.36',
    numericAnswer: 17696.36,
    tolerance: 0.1,
    baIIPlusKeystrokes: ['2ND CLR TVM', '5 N', '7.2 I/Y', '12500 +/- PV', '0 PMT', 'CPT FV'],
    trick: 'Always clear TVM and enter the investment as negative PV so the computed FV is positive.',
    explanation: 'The calculator compounds 12,500 at 7.2% for five annual periods.',
    tags: ['tvm', 'future-value'],
    difficulty: 'easy',
  },
  {
    id: 'calc-tvm-annuity-pv',
    subject: 'Quantitative Methods',
    module: 'Time Value of Money in Finance',
    skill: 'Annuity present value',
    question: 'A bond-like cash flow pays 850 at the end of each year for 6 years. If the discount rate is 8%, what is the present value?',
    expectedAnswer: '3,929.45',
    numericAnswer: 3929.45,
    tolerance: 0.1,
    baIIPlusKeystrokes: ['2ND CLR TVM', '6 N', '8 I/Y', '850 PMT', '0 FV', 'CPT PV'],
    trick: 'Ordinary annuity means END mode. Keep PMT positive and read PV as the opposite sign.',
    explanation: 'The PV is the discounted value of six equal year-end payments.',
    tags: ['tvm', 'annuity'],
    difficulty: 'easy',
  },
  {
    id: 'calc-interest-ear',
    subject: 'Quantitative Methods',
    module: 'Rates and Returns',
    skill: 'Interest conversion',
    question: 'A stated annual rate is 9% compounded monthly. What is the effective annual rate?',
    expectedAnswer: '9.38%',
    numericAnswer: 9.38,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['2ND ICONV', '9 NOM', '12 C/Y', 'CPT EFF'],
    trick: 'Use ICONV instead of typing the exponent formula when compounding frequency is given.',
    explanation: 'Monthly compounding turns the 9% nominal rate into an effective rate of about 9.38%.',
    tags: ['interest-conversion', 'ear'],
    difficulty: 'easy',
  },
  {
    id: 'calc-cashflow-npv',
    subject: 'Corporate Issuers',
    module: 'Capital Investments and Capital Allocation',
    skill: 'Uneven cash flow NPV',
    question: 'A project costs 40,000 today and produces 12,000, 14,000, 16,000, and 18,000 over the next four years. At 10%, what is NPV?',
    expectedAnswer: '6,794.62',
    numericAnswer: 6794.62,
    tolerance: 0.2,
    baIIPlusKeystrokes: ['CF', '2ND CLR WORK', '40000 +/- ENTER', 'DOWN', '12000 ENTER', 'DOWN DOWN', '14000 ENTER', 'DOWN DOWN', '16000 ENTER', 'DOWN DOWN', '18000 ENTER', 'NPV', '10 ENTER', 'DOWN', 'CPT'],
    trick: 'In the CF worksheet, use frequency 1 by pressing DOWN twice after each cash flow.',
    explanation: 'Discounting the four inflows at 10% gives a present value above the 40,000 outlay.',
    tags: ['npv', 'cash-flow'],
    difficulty: 'medium',
  },
  {
    id: 'calc-cashflow-irr',
    subject: 'Corporate Issuers',
    module: 'Capital Investments and Capital Allocation',
    skill: 'IRR',
    question: 'A project costs 25,000 today and returns 8,000 per year for 4 years. What is the IRR?',
    expectedAnswer: '10.66%',
    numericAnswer: 10.66,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['CF', '2ND CLR WORK', '25000 +/- ENTER', 'DOWN', '8000 ENTER', 'DOWN', '4 ENTER', 'IRR', 'CPT'],
    trick: 'Use the frequency field for repeated equal cash flows instead of entering 8,000 four times.',
    explanation: 'The IRR is the discount rate that makes the four 8,000 inflows equal the 25,000 outlay.',
    tags: ['irr', 'cash-flow'],
    difficulty: 'medium',
  },
  {
    id: 'calc-bond-price',
    subject: 'Fixed Income',
    module: 'Fixed-Income Bond Valuation: Prices and Yields',
    skill: 'Bond price',
    question: 'A 6% annual coupon bond has 8 years to maturity, pays semiannually, and has a YTM of 7%. What is the price per 100 par?',
    expectedAnswer: '93.95',
    numericAnswer: 93.95,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['2ND CLR TVM', '16 N', '3.5 I/Y', '3 PMT', '100 FV', 'CPT PV'],
    trick: 'For semiannual bonds, double N and halve both coupon and yield.',
    explanation: 'The bond is priced below par because its 6% coupon is below the 7% market yield.',
    tags: ['bond', 'price', 'yield'],
    difficulty: 'medium',
  },
  {
    id: 'calc-bond-ytm',
    subject: 'Fixed Income',
    module: 'Fixed-Income Bond Valuation: Prices and Yields',
    skill: 'Yield to maturity',
    question: 'A 5% annual coupon bond with 10 years to maturity sells for 92.50 per 100 par. Coupons are paid semiannually. What is the annual YTM?',
    expectedAnswer: '6.01%',
    numericAnswer: 6.01,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['2ND CLR TVM', '20 N', '92.5 +/- PV', '2.5 PMT', '100 FV', 'CPT I/Y', 'x 2'],
    trick: 'CPT I/Y gives the semiannual yield. Multiply by 2 for the bond-equivalent annual yield.',
    explanation: 'The discount price raises the yield above the 5% coupon rate.',
    tags: ['bond', 'ytm'],
    difficulty: 'medium',
  },
  {
    id: 'calc-stat-sx',
    subject: 'Quantitative Methods',
    module: 'Statistical Measures of Asset Returns',
    skill: 'Sample standard deviation',
    question: 'Returns are 4%, 7%, -2%, 9%, and 6%. What is the sample standard deviation?',
    expectedAnswer: '4.21%',
    numericAnswer: 4.21,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['2ND DATA', '2ND CLR WORK', '4 ENTER DOWN DOWN', '7 ENTER DOWN DOWN', '2 +/- ENTER DOWN DOWN', '9 ENTER DOWN DOWN', '6 ENTER', '2ND STAT', 'DOWN until Sx'],
    trick: 'For one-variable stats, keep each frequency at 1 and read Sx for sample standard deviation.',
    explanation: 'The sample standard deviation of the five returns is about 4.18 percentage points.',
    tags: ['statistics', 'standard-deviation'],
    difficulty: 'medium',
  },
  {
    id: 'calc-depreciation-straight-line',
    subject: 'Financial Statement Analysis',
    module: 'Inventories and Long-Term Assets',
    skill: 'Straight-line depreciation',
    question: 'Equipment costs 78,000, has a 6,000 salvage value, and a 9-year useful life. What is annual straight-line depreciation?',
    expectedAnswer: '8,000.00',
    numericAnswer: 8000,
    tolerance: 0.1,
    baIIPlusKeystrokes: ['78000 - 6000 =', '/ 9 ='],
    trick: 'For straight-line depreciation, direct arithmetic is faster than opening the depreciation worksheet.',
    explanation: 'Depreciable cost is 72,000, spread evenly over 9 years.',
    tags: ['depreciation', 'fsa'],
    difficulty: 'easy',
  },
  {
    id: 'calc-dupont-roe',
    subject: 'Financial Statement Analysis',
    module: 'Financial Analysis Techniques',
    skill: 'DuPont ROE',
    question: 'Net margin is 8.5%, asset turnover is 1.35, and financial leverage is 2.1. What is ROE?',
    expectedAnswer: '24.10%',
    numericAnswer: 24.1,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['8.5 x 1.35 x 2.1 ='],
    trick: 'Keep ratios in percent form only at the end: 8.5 x 1.35 x 2.1 gives percent ROE directly.',
    explanation: 'Three-part DuPont multiplies profitability, efficiency, and leverage.',
    tags: ['dupont', 'roe'],
    difficulty: 'easy',
  },
  {
    id: 'calc-fx-cross-rate',
    subject: 'Economics',
    module: 'Exchange Rate Calculations',
    skill: 'Cross rate',
    question: 'Given USD/EUR = 1.08 and USD/GBP = 1.26, what is EUR/GBP?',
    expectedAnswer: '1.1667',
    numericAnswer: 1.1667,
    tolerance: 0.0005,
    baIIPlusKeystrokes: ['1.26 / 1.08 ='],
    trick: 'Write GBP in the denominator target. USD/GBP divided by USD/EUR cancels USD and gives EUR/GBP.',
    explanation: 'One GBP costs 1.26 USD and one EUR costs 1.08 USD, so one GBP costs 1.1667 EUR.',
    tags: ['fx', 'cross-rate'],
    difficulty: 'medium',
  },
  {
    id: 'calc-duration-price-change',
    subject: 'Fixed Income',
    module: 'Interest Rate Risk and Return',
    skill: 'Duration price estimate',
    question: 'A bond has modified duration 6.4. Yield rises by 35 bps. Approximate the percentage price change.',
    expectedAnswer: '-2.24%',
    numericAnswer: -2.24,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['6.4 x .0035 x 100 +/- ='],
    trick: 'Convert basis points to decimal yield first: 35 bps = 0.0035.',
    explanation: 'Approximate price change equals negative duration times the yield change.',
    tags: ['duration', 'fixed-income'],
    difficulty: 'easy',
  },
  {
    id: 'calc-convexity-adjusted',
    subject: 'Fixed Income',
    module: 'Yield-Based Bond Convexity Measures',
    skill: 'Duration plus convexity',
    question: 'Modified duration is 7.1, convexity is 68, and yield falls by 60 bps. Estimate the percentage price change with convexity.',
    expectedAnswer: '4.38%',
    numericAnswer: 4.38,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['7.1 x .006 =', '68 x .006 x .006 x .5 =', 'add both', 'x 100'],
    trick: 'For a yield decrease, the duration effect is positive. The convexity term is positive for both rate directions.',
    explanation: 'Duration adds about 4.26%; convexity adds about 0.12%, for roughly 4.38%.',
    tags: ['convexity', 'fixed-income'],
    difficulty: 'hard',
  },
  {
    id: 'calc-put-call-parity',
    subject: 'Derivatives',
    module: 'Option Replication Using Put-Call Parity',
    skill: 'Put-call parity',
    question: 'A stock is 48, the European call is 5.20, the exercise price is 50, and PV(X) is 47.15. What is the European put price?',
    expectedAnswer: '4.35',
    numericAnswer: 4.35,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['5.20 + 47.15 - 48 ='],
    trick: 'Rearrange C + PV(X) = P + S as P = C + PV(X) - S.',
    explanation: 'The protective put side must equal the fiduciary call side.',
    tags: ['options', 'put-call-parity'],
    difficulty: 'medium',
  },
  {
    id: 'calc-forward-price',
    subject: 'Derivatives',
    module: 'Arbitrage, Replication, and Cost of Carry',
    skill: 'Forward price',
    question: 'Spot is 72, the annual risk-free rate is 5%, and maturity is 9 months. Ignore income and storage. What is the no-arbitrage forward price using annual compounding?',
    expectedAnswer: '74.68',
    numericAnswer: 74.68,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['1.05 yx .75 =', 'x 72 ='],
    trick: 'Nine months is 0.75 years. Use yx for fractional exponents.',
    explanation: 'The forward price grows spot at the risk-free rate for 0.75 years.',
    tags: ['forwards', 'cost-of-carry'],
    difficulty: 'medium',
  },
  {
    id: 'calc-alt-tvpi',
    subject: 'Alternative Investments',
    module: 'Alternative Investment Performance and Returns',
    skill: 'Private capital multiples',
    question: 'Paid-in capital is 80 million, cumulative distributions are 44 million, and residual value is 68 million. What is TVPI?',
    expectedAnswer: '1.40x',
    numericAnswer: 1.4,
    tolerance: 0.01,
    baIIPlusKeystrokes: ['44 + 68 =', '/ 80 ='],
    trick: 'TVPI combines realized value and remaining value before dividing by paid-in capital.',
    explanation: 'DPI is 0.55x and RVPI is 0.85x, so TVPI is 1.40x.',
    tags: ['alternatives', 'private-capital'],
    difficulty: 'easy',
  },
  {
    id: 'calc-portfolio-variance',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return',
    skill: 'Two-asset portfolio risk',
    question: 'A portfolio is 60% in Asset A with 18% volatility and 40% in Asset B with 11% volatility. Correlation is 0.25. What is portfolio standard deviation?',
    expectedAnswer: '12.64%',
    numericAnswer: 12.64,
    tolerance: 0.05,
    baIIPlusKeystrokes: ['.6 x .6 x .18 x .18 =', 'store or note', '.4 x .4 x .11 x .11 =', 'add', '2 x .6 x .4 x .25 x .18 x .11 =', 'add', '2ND x2 to square root', 'x 100'],
    trick: 'Use decimals for weights and volatilities, then multiply the final square root by 100.',
    explanation: 'The covariance term is positive because correlation is positive, but diversification still lowers risk below the weighted average volatility.',
    tags: ['portfolio', 'variance'],
    difficulty: 'hard',
  },
  {
    id: 'calc-capm-required-return',
    subject: 'Portfolio Management',
    module: 'Portfolio Risk and Return',
    skill: 'CAPM required return',
    question: 'The risk-free rate is 3.8%, expected market return is 9.5%, and beta is 1.25. What is the required return?',
    expectedAnswer: '10.93%',
    numericAnswer: 10.93,
    tolerance: 0.03,
    baIIPlusKeystrokes: ['9.5 - 3.8 =', 'x 1.25 =', '+ 3.8 ='],
    trick: 'Compute the market risk premium first, then multiply by beta.',
    explanation: 'CAPM adds beta-adjusted market risk premium to the risk-free rate.',
    tags: ['capm', 'required-return'],
    difficulty: 'easy',
  },
]

export const calculatorSkills = Array.from(new Set(calculatorDrills.map((drill) => drill.skill)))
