create table if not exists public.revision_library_notes (
  id text primary key,
  sort_order integer not null,
  subject text not null,
  module text not null,
  concept text not null,
  terms jsonb not null default '[]'::jsonb,
  formulas jsonb not null default '[]'::jsonb,
  trap text not null default '',
  quick_recall text not null default '',
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists revision_library_notes_subject_sort_idx
  on public.revision_library_notes (subject, sort_order);

alter table public.revision_library_notes enable row level security;

drop policy if exists "Anyone can read revision library notes" on public.revision_library_notes;
create policy "Anyone can read revision library notes"
  on public.revision_library_notes for select
  using (true);

insert into public.revision_library_notes (
  id,
  sort_order,
  subject,
  module,
  concept,
  terms,
  formulas,
  trap,
  quick_recall,
  tags
) values
  ('quant-rates-return-stack', 1, 'Quantitative Methods', 'Rates and Returns', 'Return questions usually ask whether the return is holding-period, arithmetic average, geometric average, money-weighted, time-weighted, nominal, real, gross, or net.', '["holding period return","arithmetic mean","geometric mean","money-weighted return","time-weighted return","real return"]'::jsonb, '["HPR = (ending value - beginning value + income) / beginning value","geometric mean = [(1 + R1)(1 + R2)...(1 + Rn)]^(1/n) - 1","real return approximately = nominal return - inflation","real return exactly = (1 + nominal return) / (1 + inflation) - 1"]'::jsonb, 'Arithmetic mean is best for a one-period expected return; geometric mean is best for multi-period compound performance.', 'If returns compound across time, multiply growth factors first.', '["return","compounding","formula"]'::jsonb),
  ('quant-tvm-signs', 2, 'Quantitative Methods', 'Time Value of Money in Finance', 'TVM problems are cash-flow timeline problems. The BA II Plus needs cash inflows and outflows entered with opposite signs.', '["PV","FV","PMT","N","I/Y","annuity due","ordinary annuity"]'::jsonb, '["FV = PV(1 + r)^N","PV = FV / (1 + r)^N","PV perpetuity = PMT / r","EAR = (1 + periodic rate)^m - 1"]'::jsonb, 'Leaving old TVM values in the calculator is a silent killer. Clear TVM before every fresh TVM problem.', 'Money paid out is negative; money received is positive.', '["tvm","calculator","formula"]'::jsonb),
  ('quant-statistics-risk', 3, 'Quantitative Methods', 'Statistical Measures of Asset Returns', 'Dispersion measures how spread out returns are. CFA questions often move between variance, standard deviation, coefficient of variation, and downside risk.', '["variance","standard deviation","coefficient of variation","skewness","kurtosis"]'::jsonb, '["sample variance = sum[(Xi - mean)^2] / (n - 1)","standard deviation = square root of variance","coefficient of variation = standard deviation / mean return"]'::jsonb, 'The BA II Plus sample standard deviation is Sx. Population standard deviation is sigma x. CFA samples usually use Sx unless stated otherwise.', 'Variance is squared risk; standard deviation brings risk back into return units.', '["statistics","risk","calculator"]'::jsonb),
  ('quant-probability-hypothesis', 4, 'Quantitative Methods', 'Probability, Estimation, and Hypothesis Testing', 'Probability and testing questions reward setup more than arithmetic. Identify the condition, the sample statistic, the standard error, and the rejection rule.', '["conditional probability","Bayes","standard error","confidence interval","p-value","Type I error","Type II error"]'::jsonb, '["P(A|B) = P(B|A)P(A) / P(B)","confidence interval = point estimate +/- reliability factor x standard error","t-statistic = (sample statistic - hypothesized value) / standard error"]'::jsonb, 'A small p-value means reject the null; it does not prove the alternative is economically important.', 'Type I is rejecting a true null; Type II is failing to reject a false null.', '["probability","hypothesis-testing","formula"]'::jsonb),
  ('economics-fx-cross-rates', 5, 'Economics', 'Exchange Rate Calculations', 'FX questions are quote-direction questions. Write the currency units before calculating so numerator and denominator cancel cleanly.', '["base currency","price currency","direct quote","indirect quote","cross rate","forward points"]'::jsonb, '["real exchange rate = nominal exchange rate x domestic price / foreign price","forward premium or discount approximately = forward rate / spot rate - 1","cross rate = quote 1 x quote 2 when middle currency cancels"]'::jsonb, 'If the answer is inverted, the number may look reasonable but the quote direction is wrong.', 'Treat FX like unit conversion and cancel currencies on paper.', '["fx","macro","formula"]'::jsonb),
  ('economics-fiscal-multiplier', 6, 'Economics', 'Fiscal Policy', 'Fiscal multiplier questions connect marginal propensity to consume with the total change in output from a spending shock.', '["MPC","MPS","fiscal multiplier","tax multiplier","automatic stabilizer"]'::jsonb, '["spending multiplier = 1 / (1 - MPC)","tax multiplier = -MPC / (1 - MPC)","MPS = 1 - MPC"]'::jsonb, 'Tax multipliers are smaller in absolute value than spending multipliers because households save part of the tax cut.', 'Higher MPC means a larger ripple through GDP.', '["fiscal-policy","multiplier","formula"]'::jsonb),
  ('corp-capital-budgeting', 7, 'Corporate Issuers', 'Capital Investments and Capital Allocation', 'Capital budgeting compares project cash flows against the opportunity cost of capital.', '["NPV","IRR","payback period","profitability index","mutually exclusive projects"]'::jsonb, '["NPV = PV inflows - initial outlay","profitability index = PV future cash flows / initial investment","IRR is the discount rate that sets NPV to zero"]'::jsonb, 'For mutually exclusive projects, choose the higher NPV, not necessarily the higher IRR.', 'NPV directly measures value added.', '["npv","irr","cash-flow","formula"]'::jsonb),
  ('corp-working-capital', 8, 'Corporate Issuers', 'Working Capital and Liquidity', 'Working capital ratios explain how quickly a company turns inventory and receivables into cash while using supplier financing.', '["DIO","DSO","DPO","cash conversion cycle","current ratio","quick ratio"]'::jsonb, '["cash conversion cycle = DIO + DSO - DPO","current ratio = current assets / current liabilities","quick ratio = (cash + marketable securities + receivables) / current liabilities"]'::jsonb, 'A longer DPO can improve the cash conversion cycle, but stretching suppliers can create operating risk.', 'Inventory days plus collection days minus supplier float.', '["liquidity","working-capital","formula"]'::jsonb),
  ('corp-wacc-leverage', 9, 'Corporate Issuers', 'Capital Structure', 'WACC blends required returns by capital weight and uses after-tax cost of debt because interest is tax deductible.', '["WACC","cost of debt","cost of equity","target weights","financial leverage"]'::jsonb, '["WACC = wd rd(1 - tax rate) + wp rp + we re","degree of financial leverage = EBIT / (EBIT - interest)"]'::jsonb, 'Use market value weights when available, not book weights.', 'Debt gets the tax shield; equity does not.', '["wacc","leverage","formula"]'::jsonb),
  ('fsa-income-ratios', 10, 'Financial Statement Analysis', 'Analyzing Income Statements', 'Income statement analysis separates profitability, operating efficiency, and capital structure effects.', '["gross margin","operating margin","net margin","basic EPS","diluted EPS"]'::jsonb, '["gross margin = gross profit / revenue","operating margin = operating income / revenue","net margin = net income / revenue","basic EPS = (net income - preferred dividends) / weighted average common shares"]'::jsonb, 'Diluted EPS includes potential common shares only if they reduce EPS.', 'Margins are scaled by revenue; EPS is scaled by shares.', '["income-statement","eps","formula"]'::jsonb),
  ('fsa-cash-flow-quality', 11, 'Financial Statement Analysis', 'Analyzing Statements of Cash Flows', 'Cash flow analysis checks whether earnings are converting into operating cash and whether growth is internally funded.', '["CFO","CFI","CFF","free cash flow to firm","free cash flow to equity"]'::jsonb, '["FCFF = NI + NCC + interest expense(1 - tax rate) - fixed capital investment - working capital investment","FCFE = CFO - fixed capital investment + net borrowing","cash flow performance ratio = CFO / revenue"]'::jsonb, 'Under IFRS, interest and dividends can be classified differently, so compare classifications before comparing companies.', 'FCFF belongs to all capital providers; FCFE belongs to common equity.', '["cash-flow","fcff","fcfe","formula"]'::jsonb),
  ('fsa-inventory-depreciation', 12, 'Financial Statement Analysis', 'Inventories and Long-Term Assets', 'Inventory and depreciation methods affect COGS, assets, income, ratios, and taxes.', '["FIFO","LIFO","weighted average cost","straight-line depreciation","accelerated depreciation"]'::jsonb, '["COGS = beginning inventory + purchases - ending inventory","straight-line depreciation = (cost - salvage value) / useful life","average age = accumulated depreciation / annual depreciation expense"]'::jsonb, 'In rising prices, FIFO usually reports lower COGS, higher income, higher inventory, and higher taxes than LIFO.', 'FIFO ending inventory is closer to current replacement cost.', '["inventory","depreciation","formula"]'::jsonb),
  ('fsa-dupont', 13, 'Financial Statement Analysis', 'Financial Analysis Techniques', 'DuPont analysis decomposes ROE into profitability, efficiency, and leverage drivers.', '["ROE","ROA","asset turnover","financial leverage","tax burden","interest burden"]'::jsonb, '["ROE = net income / average equity","three-part DuPont ROE = net margin x asset turnover x financial leverage","financial leverage = average assets / average equity"]'::jsonb, 'Higher ROE from leverage is not automatically better because risk may have increased.', 'Margin x turnover x leverage explains ROE.', '["dupont","ratios","formula"]'::jsonb),
  ('equity-ddm-gordon', 14, 'Equity Investments', 'Equity Valuation: Concepts and Basic Tools', 'Dividend discount models value equity as the present value of expected dividends.', '["DDM","Gordon growth model","required return","sustainable growth","retention ratio"]'::jsonb, '["V0 = D1 / (r - g)","g = retention ratio x ROE","justified P/E = payout ratio / (r - g)"]'::jsonb, 'The Gordon model only works when r is greater than g and growth is stable.', 'Next dividend over required return minus growth.', '["equity","ddm","formula"]'::jsonb),
  ('equity-indexes-multiples', 15, 'Equity Investments', 'Security Market Indexes and Valuation Multiples', 'Index and multiple questions test construction mechanics and whether a ratio is justified by fundamentals.', '["price-weighted index","market-cap-weighted index","equal-weighted index","P/E","P/B","EV/EBITDA"]'::jsonb, '["price return = (ending price - beginning price) / beginning price","total return = price return + income return","justified P/B = (ROE - g) / (r - g)"]'::jsonb, 'A high multiple can be justified by higher growth, lower risk, or higher profitability, not just overvaluation.', 'Compare multiples only after checking growth, risk, and accounting quality.', '["indexes","multiples","formula"]'::jsonb),
  ('fixed-income-bond-price', 16, 'Fixed Income', 'Fixed-Income Bond Valuation: Prices and Yields', 'A bond price is the present value of coupon cash flows plus principal, discounted at the yield per period.', '["coupon rate","yield to maturity","discount bond","premium bond","par value","current yield"]'::jsonb, '["bond price = PV coupons + PV par value","current yield = annual coupon / full price","periodic yield = annual yield / payments per year"]'::jsonb, 'Match N, I/Y, and PMT to the coupon frequency. Semiannual bonds double N and halve the annual coupon and yield.', 'Coupon rate sets PMT; market yield discounts PMT and FV.', '["bond","yield","calculator"]'::jsonb),
  ('fixed-income-duration-convexity', 17, 'Fixed Income', 'Interest Rate Risk and Return', 'Duration approximates the price impact of a yield change; convexity improves the estimate for larger yield moves.', '["Macaulay duration","modified duration","effective duration","convexity","basis point"]'::jsonb, '["approximate % price change = -modified duration x change in yield","duration plus convexity estimate = -duration x delta y + 0.5 x convexity x delta y^2"]'::jsonb, 'Use yield change in decimal form. A 50 bp increase is 0.005, not 0.50.', 'Rates up, bond prices down; convexity softens the damage.', '["duration","convexity","formula"]'::jsonb),
  ('fixed-income-spot-forward', 18, 'Fixed Income', 'The Term Structure of Interest Rates', 'Spot rates discount single future cash flows; forward rates are implied future rates that make no-arbitrage pricing hold.', '["spot rate","forward rate","par rate","yield curve","bootstrapping"]'::jsonb, '["(1 + z2)^2 = (1 + z1)(1 + 1f1)","PV cash flow = CF / (1 + spot rate)^period"]'::jsonb, 'Do not use one YTM to discount every cash flow when the question gives spot rates.', 'Each cash flow gets its own spot rate.', '["spot-rate","forward-rate","formula"]'::jsonb),
  ('derivatives-forwards-carry', 19, 'Derivatives', 'Arbitrage, Replication, and Cost of Carry', 'Forward pricing is a no-arbitrage carry problem: start with spot, add financing/storage costs, subtract benefits.', '["forward price","cost of carry","convenience yield","arbitrage","replication"]'::jsonb, '["forward price approximately = spot price x (1 + risk-free rate)^T + costs - benefits","with continuous compounding: F0 = S0 e^((r + costs - yield)T)"]'::jsonb, 'Benefits from holding the asset reduce the forward price; costs increase it.', 'Carry costs up, asset benefits down.', '["forwards","cost-of-carry","formula"]'::jsonb),
  ('derivatives-options-parity', 20, 'Derivatives', 'Option Replication Using Put-Call Parity', 'Put-call parity links a fiduciary call and a protective put for European options on non-dividend-paying stock.', '["call option","put option","fiduciary call","protective put","exercise price"]'::jsonb, '["C + PV(X) = P + S0","C - P = S0 - PV(X)"]'::jsonb, 'Parity is for European options. Early exercise features can break strict equality for American options.', 'Call plus safe bond equals put plus stock.', '["options","put-call-parity","formula"]'::jsonb),
  ('derivatives-binomial', 21, 'Derivatives', 'Valuing a Derivative Using a One-Period Binomial Model', 'The one-period binomial model values an option by risk-neutral expected payoff discounted at the risk-free rate.', '["up factor","down factor","risk-neutral probability","replication","option payoff"]'::jsonb, '["risk-neutral probability = (1 + r - d) / (u - d)","call payoff = max(0, stock price - exercise price)","option value = discounted expected payoff"]'::jsonb, 'Use terminal stock prices for payoff first, then discount the expected option payoff.', 'Payoff at the end, probability-weight, discount back.', '["binomial","options","formula"]'::jsonb),
  ('alts-performance-returns', 22, 'Alternative Investments', 'Alternative Investment Performance and Returns', 'Alternative investment returns often use money-weighted measures because cash flows are controlled by fund managers rather than investors.', '["IRR","MOIC","DPI","RVPI","TVPI","management fee","carried interest"]'::jsonb, '["MOIC = total value / paid-in capital","DPI = cumulative distributions / paid-in capital","RVPI = residual value / paid-in capital","TVPI = DPI + RVPI"]'::jsonb, 'A high TVPI with low DPI may still depend heavily on unrealized valuations.', 'DPI is cash back; RVPI is still on paper.', '["alternative-investments","private-capital","formula"]'::jsonb),
  ('portfolio-risk-return', 23, 'Portfolio Management', 'Portfolio Risk and Return', 'Portfolio risk depends on weights, asset volatilities, and correlations, not just weighted-average individual risks.', '["expected return","variance","standard deviation","correlation","diversification"]'::jsonb, '["E(Rp) = sum wi E(Ri)","two-asset variance = w1^2 sigma1^2 + w2^2 sigma2^2 + 2w1w2rho12sigma1sigma2","CAPM: E(Ri) = Rf + betai[E(Rm) - Rf]"]'::jsonb, 'Portfolio expected return is weighted average; portfolio standard deviation is not.', 'Correlation drives diversification benefit.', '["portfolio","capm","formula"]'::jsonb),
  ('portfolio-performance', 24, 'Portfolio Management', 'Portfolio Performance Measures', 'Risk-adjusted performance measures divide excess return by the relevant risk measure.', '["Sharpe ratio","Treynor ratio","Jensen alpha","M-squared","tracking error"]'::jsonb, '["Sharpe ratio = (Rp - Rf) / standard deviation of portfolio","Treynor ratio = (Rp - Rf) / beta","Jensen alpha = Rp - [Rf + beta(Rm - Rf)]"]'::jsonb, 'Use Sharpe for total risk and Treynor or Jensen alpha for systematic risk.', 'Sharpe uses sigma; Treynor uses beta.', '["performance","risk-adjusted-return","formula"]'::jsonb)
on conflict (id) do update set
  sort_order = excluded.sort_order,
  subject = excluded.subject,
  module = excluded.module,
  concept = excluded.concept,
  terms = excluded.terms,
  formulas = excluded.formulas,
  trap = excluded.trap,
  quick_recall = excluded.quick_recall,
  tags = excluded.tags,
  updated_at = now();
